// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Context.Domains.Shell;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Flux.Options;

namespace ModularPipelines.Flux.Services;

/// <summary>
/// flux pull commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public class FluxPull : IFluxPull
{
    private readonly ICommandContext _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="FluxPull"/> class.
    /// </summary>
    public FluxPull(ICommandContext command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// The pull command is used to download OCI artifacts.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ExecuteAsync(
        FluxPullOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new FluxPullOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// The pull artifact command downloads and extracts the OCI artifact content to the given path.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ArtifactAsync(
        FluxPullArtifactOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new FluxPullArtifactOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
