<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks />
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <EnableAotAnalyzer>true</EnableAotAnalyzer>
    <InvariantGlobalization>true</InvariantGlobalization>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL2046;IL2060;IL2070;IL2071;IL2075;IL2091;IL3050</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="PublishAot" />
    <CompilerVisibleProperty Include="PublishTrimmed" />
    <ProjectReference Include="..\..\src\ModularPipelines\ModularPipelines.csproj" />
    <ProjectReference
      Include="..\..\src\ModularPipelines.SourceGenerator\ModularPipelines.SourceGenerator.csproj"
      ReferenceOutputAssembly="false"
      OutputItemType="Analyzer"
      SetTargetFramework="TargetFramework=netstandard2.0" />
  </ItemGroup>
</Project>
