// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.GitHub.Options;

namespace ModularPipelines.GitHub.Services;

/// <summary>
/// gh project commands.
/// </summary>
/// <remarks>
/// Nested sub-command groups are exposed as concrete services; only this top-level facade is interface-backed.
/// </remarks>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public interface IGhProject
{
    /// <summary>
    /// Work with GitHub Projects.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ExecuteAsync(GhProjectOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Close a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> CloseAsync(GhProjectCloseOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Copy a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> CopyAsync(GhProjectCopyOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Create a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> CreateAsync(GhProjectCreateOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Delete a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> DeleteAsync(GhProjectDeleteOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Edit a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> EditAsync(GhProjectEditOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Create a field in a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> FieldCreateAsync(GhProjectFieldCreateOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Delete a field in a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> FieldDeleteAsync(GhProjectFieldDeleteOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// List the fields in a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> FieldListAsync(GhProjectFieldListOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Add a pull request or an issue to a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ItemAddAsync(GhProjectItemAddOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Archive an item in a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ItemArchiveAsync(GhProjectItemArchiveOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Create a draft issue item in a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ItemCreateAsync(GhProjectItemCreateOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Delete an item from a project by ID
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ItemDeleteAsync(GhProjectItemDeleteOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Edit a draft issue or a project item.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ItemEditAsync(GhProjectItemEditOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// List the items in a project.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ItemListAsync(GhProjectItemListOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Link a project to a repository or a team
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> LinkAsync(GhProjectLinkOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// List the projects for an owner
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ListAsync(GhProjectListOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Mark a project as a template
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> MarkTemplateAsync(GhProjectMarkTemplateOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// Unlink a project from a repository or a team
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> UnlinkAsync(GhProjectUnlinkOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

    /// <summary>
    /// View a project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public Task<CommandResult> ViewAsync(GhProjectViewOptions? options = null, CommandExecutionOptions? executionOptions = null, CancellationToken cancellationToken = default)
        => throw new System.NotSupportedException();

}
