// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigatewayv2/delete-integration-response/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Deletes an IntegrationResponses. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("apigatewayv2", "delete-integration-response")]
public record AwsApigatewayv2DeleteIntegrationResponseOptions : AwsOptions
{
    [CliOption("--api-id")]
    public string? ApiId { get; set; }

    [CliOption("--integration-id")]
    public string? IntegrationId { get; set; }

    [CliOption("--integration-response-id")]
    public string? IntegrationResponseId { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

}
