// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/braket/cancel-quantum-task/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using ModularPipelines.Secrets;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Cancels the specified task. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("braket", "cancel-quantum-task")]
public record AwsBraketCancelQuantumTaskOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Cancels the specified task. See also: AWS API Documentation
    /// </summary>
    /// <param name="QuantumTaskArn">The ARN of the quantum task to cancel. Constraints: o min: 0 o max: 256</param>
    public AwsBraketCancelQuantumTaskOptions(
        string QuantumTaskArn
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(QuantumTaskArn);
        this.QuantumTaskArn = QuantumTaskArn;
    }

    private AwsBraketCancelQuantumTaskOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsBraketCancelQuantumTaskOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsBraketCancelQuantumTaskOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The ARN of the quantum task to cancel. Constraints: o min: 0 o max: 256
    /// </summary>
    [CliOption("--quantum-task-arn")]
    public string? QuantumTaskArn { get; private init; }

    /// <summary>
    /// The client token associated with the cancellation request. Constraints: o min: 1 o max: 64
    /// </summary>
    [SecretValue]
    [CliOption("--client-token")]
    public string? ClientToken { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

        yield break;
    }

}
