// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/codecommit/update-pull-request-title/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Replaces the title of a pull request. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("codecommit", "update-pull-request-title")]
public record AwsCodecommitUpdatePullRequestTitleOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Replaces the title of a pull request. See also: AWS API Documentation
    /// </summary>
    /// <param name="PullRequestId">The system-generated ID of the pull request. To get this ID, use ListPullRequests .</param>
    /// <param name="Title">The updated title of the pull request. This replaces the existing title. Constraints: o max: 150</param>
    public AwsCodecommitUpdatePullRequestTitleOptions(
        string PullRequestId,
        string Title
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(PullRequestId);
        this.PullRequestId = PullRequestId;
        global::System.ArgumentNullException.ThrowIfNull(Title);
        this.Title = Title;
    }

    private AwsCodecommitUpdatePullRequestTitleOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsCodecommitUpdatePullRequestTitleOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsCodecommitUpdatePullRequestTitleOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The system-generated ID of the pull request. To get this ID, use ListPullRequests .
    /// </summary>
    [CliOption("--pull-request-id")]
    public string? PullRequestId { get; private init; }

    /// <summary>
    /// The updated title of the pull request. This replaces the existing title. Constraints: o max: 150
    /// </summary>
    [CliOption("--title")]
    public string? Title { get; private init; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

    }

}
