// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/list-stack-set-auto-deployment-targets/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using ModularPipelines.Secrets;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;
using ModularPipelines.AmazonWebServices.Enums;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Returns summary information about deployment targets for a StackSet. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("cloudformation", "list-stack-set-auto-deployment-targets")]
public record AwsCloudformationListStackSetAutoDeploymentTargetsOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Returns summary information about deployment targets for a StackSet. See also: AWS API Documentation
    /// </summary>
    /// <param name="StackSetName">The name or unique ID of the StackSet that you want to get automatic deployment targets for. Constraints: o pattern: [a-zA-Z][-a-zA-Z0-9]*(?::[a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12})?</param>
    public AwsCloudformationListStackSetAutoDeploymentTargetsOptions(
        string StackSetName
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(StackSetName);
        this.StackSetName = StackSetName;
    }

    private AwsCloudformationListStackSetAutoDeploymentTargetsOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsCloudformationListStackSetAutoDeploymentTargetsOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsCloudformationListStackSetAutoDeploymentTargetsOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The name or unique ID of the StackSet that you want to get automatic deployment targets for. Constraints: o pattern: [a-zA-Z][-a-zA-Z0-9]*(?::[a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12})?
    /// </summary>
    [CliOption("--stack-set-name")]
    public string? StackSetName { get; private init; }

    /// <summary>
    /// The token for the next set of items to return. (You received this token from a previous call.) Constraints: o min: 1 o max: 1024
    /// </summary>
    [SecretValue]
    [CliOption("--next-token")]
    public string? NextToken { get; set; }

    /// <summary>
    /// The maximum number of results to be returned with a single call. If the number of available results exceeds this maximum, the response includes a NextToken value that you can assign to the NextToken re- quest parameter to get the next set of results. Constraints: o min: 1 o max: 100
    /// </summary>
    [CliOption("--max-results")]
    public int? MaxResults { get; set; }

    /// <summary>
    /// Specifies whether you are acting as an account administrator in the organization's management account or as a delegated administrator in a member account. By default, SELF is specified. Use SELF for StackSets with self-man- aged permissions. o If you are signed in to the management account, specify SELF . o If you are signed in to a delegated administrator account, specify DELEGATED_ADMIN . Your Amazon Web Services account must be regis- tered as a delegated administrator in the management account. For more information, see Register a delegated administrator in the CloudFormation User Guide . Possible values: o SELF o DELEGATED_ADMIN
    /// </summary>
    [CliOption("--call-as")]
    public AwsCloudformationListStackSetAutoDeploymentTargetsCallAs? CallAs { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

        yield break;
    }

}
