// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudfront/update-distribution-tenant/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Updates a distribution tenant. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("cloudfront", "update-distribution-tenant")]
public record AwsCloudfrontUpdateDistributionTenantOptions : AwsOptions
{
    [CliOption("--id")]
    public string? Id { get; set; }

    /// <summary>
    /// The ID for the multi-tenant distribution.
    /// </summary>
    [CliOption("--distribution-id")]
    public string? DistributionId { get; set; }

    /// <summary>
    /// The domains to update for the distribution tenant. A domain object can contain only a domain property. You must specify at least one domain. Each distribution tenant can have up to 5 domains. (structure) The domain for the specified distribution tenant. Domain -&gt; (string) [required] The domain name. Shorthand Syntax: Domain=string ... JSON Syntax: [ { "Domain": "string" } ... ]
    /// </summary>
    [CliOption("--domains", GroupValues = true)]
    public IEnumerable<string>? Domains { get; set; }

    /// <summary>
    /// Customizations for the distribution tenant. For each distribution tenant, you can specify the geographic restrictions, and the Amazon Resource Names (ARNs) for the ACM certificate and WAF web ACL. These are specific values that you can override or disable from the multi-tenant distribution that was used to create the distribution tenant. WebAcl -&gt; (structure) The WAF web ACL. Action -&gt; (string) [required] The action for the WAF web ACL customization. You can specify override to specify a separate WAF web ACL for the distribu- tion tenant. If you specify disable , the distribution tenant won't have WAF web ACL protections and won't inherit from the multi-tenant distribution. Possible values: o override o disable Arn -&gt; (string) The Amazon Resource Name (ARN) of the WAF web ACL. Certificate -&gt; (structure) The Certificate Manager (ACM) certificate. Arn -&gt; (string) [required] The Amazon Resource Name (ARN) of the ACM certificate. GeoRestrictions -&gt; (structure) The geographic restrictions. RestrictionType -&gt; (string) [required] The method that you want to use to restrict distribution of your content by country: o none : No geographic restriction is enabled, meaning access to content is not restricted by client geo location. o blacklist : The Location elements specify the countries in which you don't want CloudFront to distribute your content. o whitelist : The Location elements specify the countries in which you want CloudFront to distribute your content. Possible values: o blacklist o whitelist o none Locations -&gt; (list) The locations for geographic restrictions. (string) Shorthand Syntax: WebAcl={Action=string,Arn=string},Certificate={Arn=string},GeoRestrictions={RestrictionType=string,Locations=[string,string]} JSON Syntax: { "WebAcl": { "Action": "override"|"disable", "Arn": "string" }, "Certificate": { "Arn": "string" }, "GeoRestrictions": { "RestrictionType": "blacklist"|"whitelist"|"none", "Locations": ["string", ...] } }
    /// </summary>
    [CliOption("--customizations")]
    public string? Customizations { get; set; }

    /// <summary>
    /// A list of parameter values to add to the resource. A parameter is specified as a key-value pair. A valid parameter value must exist for any parameter that is marked as required in the multi-tenant distribution. (structure) A list of parameter values to add to the resource. A parameter is specified as a key-value pair. A valid parameter value must exist for any parameter that is marked as required in the multi-tenant distribution. Name -&gt; (string) [required] The parameter name. Constraints: o min: 1 o max: 128 o pattern: [a-zA-Z0-9-_]+ Value -&gt; (string) [required] The parameter value. Constraints: o min: 1 o max: 256 Shorthand Syntax: Name=string,Value=string ... JSON Syntax: [ { "Name": "string", "Value": "string" } ... ]
    /// </summary>
    [CliOption("--parameters", GroupValues = true)]
    public IEnumerable<string>? Parameters { get; set; }

    /// <summary>
    /// The ID of the target connection group.
    /// </summary>
    [CliOption("--connection-group-id")]
    public string? ConnectionGroupId { get; set; }

    [CliOption("--if-match")]
    public string? IfMatch { get; set; }

    /// <summary>
    /// An object that contains the CloudFront managed ACM certificate re- quest. ValidationTokenHost -&gt; (string) [required] Specify how the HTTP validation token will be served when re- questing the CloudFront managed ACM certificate. o For cloudfront , CloudFront will automatically serve the vali- dation token. Choose this mode if you can point the domain's DNS to CloudFront immediately. o For self-hosted , you serve the validation token from your ex- isting infrastructure. Choose this mode when you need to main- tain current traffic flow while your certificate is being is- sued. You can place the validation token at the well-known path on your existing web server, wait for ACM to validate and issue the certificate, and then update your DNS to point to CloudFront. Possible values: o cloudfront o self-hosted PrimaryDomainName -&gt; (string) The primary domain name associated with the CloudFront managed ACM certificate. CertificateTransparencyLoggingPreference -&gt; (string) You can opt out of certificate transparency logging by specify- ing the disabled option. Opt in by specifying enabled . For more information, see Certificate Transparency Logging in the Cer- tificate Manager User Guide . Possible values: o enabled o disabled Shorthand Syntax: ValidationTokenHost=string,PrimaryDomainName=string,CertificateTransparencyLoggingPreference=string JSON Syntax: { "ValidationTokenHost": "cloudfront"|"self-hosted", "PrimaryDomainName": "string", "CertificateTransparencyLoggingPreference": "enabled"|"disabled" }
    /// </summary>
    [CliOption("--managed-certificate-request")]
    public string? ManagedCertificateRequest { get; set; }

    /// <summary>
    /// Indicates whether the distribution tenant should be updated to an enabled state. If you update the distribution tenant and it's not enabled, the distribution tenant won't serve traffic.
    /// </summary>
    [CliFlag("--enabled", NegatedName = "--no-enabled")]
    public bool? Enabled { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

}
