// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecr/delete-pull-through-cache-rule/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Deletes a pull through cache rule. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("ecr", "delete-pull-through-cache-rule")]
public record AwsEcrDeletePullThroughCacheRuleOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Deletes a pull through cache rule. See also: AWS API Documentation
    /// </summary>
    /// <param name="EcrRepositoryPrefix">The Amazon ECR repository prefix associated with the pull through cache rule to delete. Constraints: o min: 2 o max: 30 o pattern: ^([a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*\/?|ROOT)$</param>
    public AwsEcrDeletePullThroughCacheRuleOptions(
        string EcrRepositoryPrefix
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(EcrRepositoryPrefix);
        this.EcrRepositoryPrefix = EcrRepositoryPrefix;
    }

    private AwsEcrDeletePullThroughCacheRuleOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsEcrDeletePullThroughCacheRuleOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsEcrDeletePullThroughCacheRuleOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The Amazon ECR repository prefix associated with the pull through cache rule to delete. Constraints: o min: 2 o max: 30 o pattern: ^([a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*(\/[a-z0-9]+((\.|_|__|-+)[a-z0-9]+)*)*\/?|ROOT)$
    /// </summary>
    [CliOption("--ecr-repository-prefix")]
    public string? EcrRepositoryPrefix { get; private init; }

    /// <summary>
    /// The Amazon Web Services account ID associated with the registry that contains the pull through cache rule. If you do not specify a reg- istry, the default registry is assumed. Constraints: o pattern: [0-9]{12}
    /// </summary>
    [CliOption("--registry-id")]
    public string? RegistryId { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

    }

}
