// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/disable-ipam-organization-admin-account/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Disable the IPAM account. For more information, see Enable integration with Organizations in the Amazon VPC IPAM User Guide . See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("ec2", "disable-ipam-organization-admin-account")]
public record AwsEc2DisableIpamOrganizationAdminAccountOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Disable the IPAM account. For more information, see Enable integration with Organizations in the Amazon VPC IPAM User Guide . See also: AWS API Documentation
    /// </summary>
    /// <param name="DelegatedAdminAccountId">The Organizations member account ID that you want to disable as IPAM account.</param>
    public AwsEc2DisableIpamOrganizationAdminAccountOptions(
        string DelegatedAdminAccountId
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(DelegatedAdminAccountId);
        this.DelegatedAdminAccountId = DelegatedAdminAccountId;
    }

    private AwsEc2DisableIpamOrganizationAdminAccountOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsEc2DisableIpamOrganizationAdminAccountOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsEc2DisableIpamOrganizationAdminAccountOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The Organizations member account ID that you want to disable as IPAM account.
    /// </summary>
    [CliOption("--delegated-admin-account-id")]
    public string? DelegatedAdminAccountId { get; private init; }

    /// <summary>
    /// A check for whether you have the required permissions for the action without actually making the request and provides an error response. If you have the required permissions, the error response is DryRun- Operation . Otherwise, it is UnauthorizedOperation .
    /// </summary>
    [CliFlag("--dry-run", NegatedName = "--no-dry-run")]
    public bool? DryRun { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

    }

}
