// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/guardduty/get-trusted-entity-set/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Retrieves the trusted entity set associated with the specified truste- dEntitySetId . See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("guardduty", "get-trusted-entity-set")]
public record AwsGuarddutyGetTrustedEntitySetOptions : AwsOptions
{
    [CliOption("--detector-id")]
    public string? DetectorId { get; set; }

    [CliOption("--trusted-entity-set-id")]
    public string? TrustedEntitySetId { get; set; }

    [CliFlag("--cli-input-json")]
    public bool? CliInputJson { get; set; }

    [CliFlag("--generate-cli-skeleton")]
    public bool? GenerateCliSkeleton { get; set; }

}
