// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kendra/list-entity-personas/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Lists specific permissions of users and groups with access to your Ama- zon Kendra experience. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("kendra", "list-entity-personas")]
public record AwsKendraListEntityPersonasOptions : AwsOptions
{
    [CliOption("--id")]
    public string? Id { get; set; }

    [CliOption("--index-id")]
    public string? IndexId { get; set; }

    /// <summary>
    /// If the previous response was incomplete (because there is more data to retrieve), Amazon Kendra returns a pagination token in the re- sponse. You can use this pagination token to retrieve the next set of users or groups. Constraints: o min: 1 o max: 800
    /// </summary>
    [SecretValue]
    [CliOption("--next-token")]
    public string? NextToken { get; set; }

    /// <summary>
    /// The maximum number of returned users or groups. Constraints: o min: 1 o max: 100
    /// </summary>
    [CliOption("--max-results")]
    public int? MaxResults { get; set; }

    [CliFlag("--cli-input-json")]
    public bool? CliInputJson { get; set; }

    [CliFlag("--generate-cli-skeleton")]
    public bool? GenerateCliSkeleton { get; set; }

}
