// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/kendra/list-groups-older-than-ordering-id/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Provides a list of groups that are mapped to users before a given or- dering or timestamp identifier. ListGroupsOlderThanOrderingId is currently not supported in the Ama- zon Web Services GovCloud (US-West) region. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("kendra", "list-groups-older-than-ordering-id")]
public record AwsKendraListGroupsOlderThanOrderingIdOptions : AwsOptions
{
    [CliOption("--index-id")]
    public string? IndexId { get; set; }

    /// <summary>
    /// The identifier of the data source for getting a list of groups mapped to users before a given ordering timestamp identifier. Constraints: o min: 1 o max: 100 o pattern: [a-zA-Z0-9][a-zA-Z0-9_-]*
    /// </summary>
    [CliOption("--data-source-id")]
    public string? DataSourceId { get; set; }

    [CliOption("--ordering-id")]
    public int? OrderingId { get; set; }

    /// <summary>
    /// If the previous response was incomplete (because there is more data to retrieve), Amazon Kendra returns a pagination token in the re- sponse. You can use this pagination token to retrieve the next set of groups that are mapped to users before a given ordering or time- stamp identifier. Constraints: o min: 1 o max: 800
    /// </summary>
    [SecretValue]
    [CliOption("--next-token")]
    public string? NextToken { get; set; }

    /// <summary>
    /// The maximum number of returned groups that are mapped to users be- fore a given ordering or timestamp identifier. Constraints: o min: 1 o max: 10
    /// </summary>
    [CliOption("--max-results")]
    public int? MaxResults { get; set; }

    [CliFlag("--cli-input-json")]
    public bool? CliInputJson { get; set; }

    [CliFlag("--generate-cli-skeleton")]
    public bool? GenerateCliSkeleton { get; set; }

}
