// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lookoutequipment/describe-dataset/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Provides a JSON description of the data in each time series dataset, including names, column names, and data types. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("lookoutequipment", "describe-dataset")]
public record AwsLookoutequipmentDescribeDataSetOptions : AwsOptions
{
    [CliOption("--dataset-name")]
    public string? DataSetName { get; set; }

    [CliFlag("--cli-input-json")]
    public bool? CliInputJson { get; set; }

    [CliFlag("--generate-cli-skeleton")]
    public bool? GenerateCliSkeleton { get; set; }

}
