// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/opensearch/create-index/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Creates an OpenSearch index with optional automatic semantic enrichment for specified text fields. Automatic semantic enrichment enables seman- tic search capabilities without requiring machine learning expertise, improving search relevance by up to 20% by understanding search intent and contextual meaning beyond keyword matching. The semantic enrichment process has zero impact on search latency as sparse encodings are stored directly within the index during indexing. For more information, see A...
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("opensearch", "create-index")]
public record AwsOpensearchCreateIndexOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Creates an OpenSearch index with optional automatic semantic enrichment for specified text fields. Automatic semantic enrichment enables seman- tic search capabilities without requiring machine learning expertise, improving search relevance by up to 20% by understanding search intent and contextual meaning beyond keyword matching. The semantic enrichment process has zero impact on search latency as sparse encodings are stored directly within the index during indexing. For more information, see A...
    /// </summary>
    /// <param name="DomainName">The name of an OpenSearch Service domain. Domain names are unique across the domains owned by an account within an Amazon Web Services Region. Constraints: o min: 3 o max: 28 o pattern: [a-z][a-z0-9\-]+</param>
    /// <param name="IndexName">The name of the index to create. Must be between 1 and 255 charac- ters and follow OpenSearch naming conventions. Constraints: o min: 1 o max: 255 o pattern: ^(?!\.\.?$)[^_ ,:"+/*\\|?#&gt;&lt;A-Z-][^ ,:"+/*\\|?#&gt;&lt;A-Z]*$</param>
    /// <param name="IndexSchema">The JSON schema defining index mappings, settings, and semantic en- richment configuration. The schema specifies which text fields should be automatically enriched for semantic search capabilities and includes OpenSearch index configuration parameters. JSON Syntax: {...}</param>
    public AwsOpensearchCreateIndexOptions(
        string DomainName,
        string IndexName,
        string IndexSchema
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(DomainName);
        this.DomainName = DomainName;
        global::System.ArgumentNullException.ThrowIfNull(IndexName);
        this.IndexName = IndexName;
        global::System.ArgumentNullException.ThrowIfNull(IndexSchema);
        this.IndexSchema = IndexSchema;
    }

    private AwsOpensearchCreateIndexOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsOpensearchCreateIndexOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsOpensearchCreateIndexOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The name of an OpenSearch Service domain. Domain names are unique across the domains owned by an account within an Amazon Web Services Region. Constraints: o min: 3 o max: 28 o pattern: [a-z][a-z0-9\-]+
    /// </summary>
    [CliOption("--domain-name")]
    public string? DomainName { get; private init; }

    /// <summary>
    /// The name of the index to create. Must be between 1 and 255 charac- ters and follow OpenSearch naming conventions. Constraints: o min: 1 o max: 255 o pattern: ^(?!\.\.?$)[^_ ,:"+/*\\|?#&gt;&lt;A-Z-][^ ,:"+/*\\|?#&gt;&lt;A-Z]*$
    /// </summary>
    [CliOption("--index-name")]
    public string? IndexName { get; private init; }

    /// <summary>
    /// The JSON schema defining index mappings, settings, and semantic en- richment configuration. The schema specifies which text fields should be automatically enriched for semantic search capabilities and includes OpenSearch index configuration parameters. JSON Syntax: {...}
    /// </summary>
    [CliOption("--index-schema")]
    public string? IndexSchema { get; private init; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

    }

}
