// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/pinpoint-sms-voice-v2/get-protect-configuration-country-rule-set/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Retrieve the CountryRuleSet for the specified NumberCapability from a protect configuration. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("pinpoint-sms-voice-v2", "get-protect-configuration-country-rule-set")]
public record AwsPinpointSmsVoiceV2GetProtectConfigurationCountryRuleSetOptions : AwsOptions
{
    [CliOption("--protect-configuration-id")]
    public string? ProtectConfigurationId { get; set; }

    [CliOption("--number-capability")]
    public string? NumberCapability { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

}
