// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/quicksight/describe-self-upgrade-configuration/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Describes the self-upgrade configuration for a Quick account. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("quicksight", "describe-self-upgrade-configuration")]
public record AwsQuicksightDescribeSelfUpgradeConfigurationOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Describes the self-upgrade configuration for a Quick account. See also: AWS API Documentation
    /// </summary>
    /// <param name="AwsAccountId">The ID of the Amazon Web Services account that contains the Quick self-upgrade configuration. Constraints: o min: 12 o max: 12 o pattern: ^[0-9]{12}$</param>
    /// <param name="Namespace">The Quick namespace that you want to describe the Quick self-upgrade configuration for. Constraints: o max: 64 o pattern: ^[a-zA-Z0-9._-]*$</param>
    public AwsQuicksightDescribeSelfUpgradeConfigurationOptions(
        string AwsAccountId,
        string Namespace
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(AwsAccountId);
        this.AwsAccountId = AwsAccountId;
        global::System.ArgumentNullException.ThrowIfNull(Namespace);
        this.Namespace = Namespace;
    }

    private AwsQuicksightDescribeSelfUpgradeConfigurationOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsQuicksightDescribeSelfUpgradeConfigurationOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsQuicksightDescribeSelfUpgradeConfigurationOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The ID of the Amazon Web Services account that contains the Quick self-upgrade configuration. Constraints: o min: 12 o max: 12 o pattern: ^[0-9]{12}$
    /// </summary>
    [CliOption("--aws-account-id")]
    public string? AwsAccountId { get; private init; }

    /// <summary>
    /// The Quick namespace that you want to describe the Quick self-upgrade configuration for. Constraints: o max: 64 o pattern: ^[a-zA-Z0-9._-]*$
    /// </summary>
    [CliOption("--namespace")]
    public string? Namespace { get; private init; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

        yield break;
    }

}
