// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ram/get-permission/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Retrieves the contents of a managed permission in JSON format. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("ram", "get-permission")]
public record AwsRamGetPermissionOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Retrieves the contents of a managed permission in JSON format. See also: AWS API Documentation
    /// </summary>
    /// <param name="PermissionArn">Specifies the Amazon Resource Name (ARN) of the permission whose contents you want to retrieve. To find the ARN for a permission, use either the ListPermissions operation or go to the Permissions li- brary page in the RAM console and then choose the name of the per- mission. The ARN is displayed on the detail page.</param>
    public AwsRamGetPermissionOptions(
        string PermissionArn
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(PermissionArn);
        this.PermissionArn = PermissionArn;
    }

    private AwsRamGetPermissionOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsRamGetPermissionOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsRamGetPermissionOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// Specifies the Amazon Resource Name (ARN) of the permission whose contents you want to retrieve. To find the ARN for a permission, use either the ListPermissions operation or go to the Permissions li- brary page in the RAM console and then choose the name of the per- mission. The ARN is displayed on the detail page.
    /// </summary>
    [CliOption("--permission-arn")]
    public string? PermissionArn { get; private init; }

    /// <summary>
    /// Specifies the version number of the RAM permission to retrieve. If you don't specify this parameter, the operation retrieves the de- fault version. To see the list of available versions, use ListPermissionVersions .
    /// </summary>
    [CliOption("--permission-version")]
    public int? PermissionVersion { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

        yield break;
    }

}
