// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/add-role-to-db-cluster/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Associates an Identity and Access Management (IAM) role with a DB clus- ter. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("rds", "add-role-to-db-cluster")]
public record AwsRdsAddRoleToDbClusterOptions : AwsOptions
{
    [CliOption("--db-cluster-identifier")]
    public string? DbClusterIdentifier { get; set; }

    [CliOption("--role-arn")]
    public string? RoleArn { get; set; }

    /// <summary>
    /// The name of the feature for the DB cluster that the IAM role is to be associated with. For information about supported feature names, see DBEngineVersion .
    /// </summary>
    [CliOption("--feature-name")]
    public string? FeatureName { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

}
