// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/route53globalresolver/get-access-source/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Retrieves information about an access source. WARNING: Route 53 Global Resolver is a global service that supports resolvers in multiple Amazon Web Services Regions but you must specify the US East (Ohio) Region to create, update, or otherwise work with Route 53 Global Resolver resources. That is, for example, specify --region us-east-2 on Amazon Web Services CLI commands. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("route53globalresolver", "get-access-source")]
public record AwsRoute53globalresolverGetAccessSourceOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Retrieves information about an access source. WARNING: Route 53 Global Resolver is a global service that supports resolvers in multiple Amazon Web Services Regions but you must specify the US East (Ohio) Region to create, update, or otherwise work with Route 53 Global Resolver resources. That is, for example, specify --region us-east-2 on Amazon Web Services CLI commands. See also: AWS API Documentation
    /// </summary>
    /// <param name="AccessSourceId">The unique identifier of the access source to retrieve. Constraints: o min: 1 o max: 64 o pattern: [-.a-zA-Z0-9]+</param>
    public AwsRoute53globalresolverGetAccessSourceOptions(
        string AccessSourceId
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(AccessSourceId);
        this.AccessSourceId = AccessSourceId;
    }

    private AwsRoute53globalresolverGetAccessSourceOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsRoute53globalresolverGetAccessSourceOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsRoute53globalresolverGetAccessSourceOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The unique identifier of the access source to retrieve. Constraints: o min: 1 o max: 64 o pattern: [-.a-zA-Z0-9]+
    /// </summary>
    [CliOption("--access-source-id")]
    public string? AccessSourceId { get; private init; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

    }

}
