// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/stepfunctions/list-map-runs/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using ModularPipelines.Secrets;
using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using System.ComponentModel.DataAnnotations;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Lists all Map Runs that were started by a given state machine execu- tion. Use this API action to obtain Map Run ARNs, and then call De- scribeMapRun to obtain more information, if needed. See also: AWS API Documentation list-map-runs is a paginated operation. Multiple API calls may be is- sued in order to retrieve the entire data set of results. You can dis- able pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --...
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("stepfunctions", "list-map-runs")]
public record AwsStepfunctionsListMapRunsOptions : AwsOptions, IValidatableObject
{
    private readonly bool _requiresAlternateInput;

    /// <summary>
    /// Lists all Map Runs that were started by a given state machine execu- tion. Use this API action to obtain Map Run ARNs, and then call De- scribeMapRun to obtain more information, if needed. See also: AWS API Documentation list-map-runs is a paginated operation. Multiple API calls may be is- sued in order to retrieve the entire data set of results. You can dis- able pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --...
    /// </summary>
    /// <param name="ExecutionArn">The Amazon Resource Name (ARN) of the execution for which the Map Runs must be listed. Constraints: o min: 1 o max: 256</param>
    public AwsStepfunctionsListMapRunsOptions(
        string ExecutionArn
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(ExecutionArn);
        this.ExecutionArn = ExecutionArn;
    }

    private AwsStepfunctionsListMapRunsOptions()
    {
        _requiresAlternateInput = true;
    }

    public static AwsStepfunctionsListMapRunsOptions FromCliInputJson(string cliInputJson)
    {
        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(cliInputJson);
        return new() { CliInputJson = cliInputJson };
    }

    public static AwsStepfunctionsListMapRunsOptions ForCliSkeleton(string generateCliSkeleton = "input") =>
        generateCliSkeleton is "input" or "yaml-input"
            ? new() { GenerateCliSkeleton = generateCliSkeleton }
            : throw new global::System.ArgumentOutOfRangeException(
                nameof(generateCliSkeleton),
                generateCliSkeleton,
                "Required operation values may only be omitted for input or yaml-input skeletons.");

    /// <summary>
    /// The Amazon Resource Name (ARN) of the execution for which the Map Runs must be listed. Constraints: o min: 1 o max: 256
    /// </summary>
    [CliOption("--execution-arn")]
    public string? ExecutionArn { get; private init; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

    /// <summary>
    /// A token to specify where to start paginating. This is the NextToken from a previously truncated response. For usage examples, see Pagination in the AWS Command Line Interface User Guide .
    /// </summary>
    [SecretValue]
    [CliOption("--starting-token")]
    public string? StartingToken { get; set; }

    /// <summary>
    /// The size of each page to get in the AWS service call. This does not affect the number of items returned in the command's output. Setting a smaller page size results in more calls to the AWS service, re- trieving fewer items in each call. This can help prevent the AWS service calls from timing out. For usage examples, see Pagination in the AWS Command Line Interface User Guide . Constraints: o min: 0 o max: 1000
    /// </summary>
    [CliOption("--page-size")]
    public int? PageSize { get; set; }

    /// <summary>
    /// The total number of items to return in the command's output. If the total number of items available is more than the value specified, a NextToken is provided in the command's output. To resume pagination, provide the NextToken value in the starting-token argument of a sub- sequent command. Do not use the NextToken response element directly outside of the AWS CLI. For usage examples, see Pagination in the AWS Command Line Interface User Guide .
    /// </summary>
    [CliOption("--max-items")]
    public int? MaxItems { get; set; }

    /// <inheritdoc />
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        if (_requiresAlternateInput && !(!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input"))
        {
            yield return new ValidationResult("An alternate input must remain selected for an instance created without required operation values.");
            yield break;
        }

        if (!string.IsNullOrWhiteSpace(CliInputJson) || GenerateCliSkeleton is "input" or "yaml-input")
        {
            yield break;
        }

    }

}
