// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/sagemaker/delete-studio-lifecycle-config/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Deletes the Amazon SageMaker AI Studio Lifecycle Configuration. In or- der to delete the Lifecycle Configuration, there must be no running apps using the Lifecycle Configuration. You must also remove the Life- cycle Configuration from UserSettings in all Domains and UserProfiles. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("sagemaker", "delete-studio-lifecycle-config")]
public record AwsSagemakerDeleteStudioLifecycleConfigOptions : AwsOptions
{
    [CliOption("--studio-lifecycle-config-name")]
    public string? StudioLifecycleConfigName { get; set; }

    [CliOption("--cli-input-json")]
    public string? CliInputJson { get; set; }

    [CliOption("--generate-cli-skeleton")]
    public string? GenerateCliSkeleton { get; set; }

}
