// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/wellarchitected/update-global-settings/index.html
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.AmazonWebServices.Options;
using ModularPipelines.AmazonWebServices.Enums;

namespace ModularPipelines.AmazonWebServices.Options;

/// <summary>
/// Update whether the Amazon Web Services account is opted into organiza- tion sharing and discovery integration features. See also: AWS API Documentation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("wellarchitected", "update-global-settings")]
public record AwsWellarchitectedUpdateGlobalSettingsOptions : AwsOptions
{
    /// <summary>
    /// The status of organization sharing settings. Possible values: o ENABLED o DISABLED
    /// </summary>
    [CliOption("--organization-sharing-status")]
    public AwsWellarchitectedUpdateGlobalSettingsOrganizationSharingStatus? OrganizationSharingStatus { get; set; }

    /// <summary>
    /// The status of discovery support settings. Possible values: o ENABLED o DISABLED
    /// </summary>
    [CliOption("--discovery-integration-status")]
    public AwsWellarchitectedUpdateGlobalSettingsDiscoveryIntegrationStatus? DiscoveryIntegrationStatus { get; set; }

    /// <summary>
    /// The status of Jira integration settings. IssueManagementStatus -&gt; (string) Account-level: Jira issue management status. Possible values: o ENABLED o DISABLED IssueManagementType -&gt; (string) Account-level: Jira issue management type. Possible values: o AUTO o MANUAL JiraProjectKey -&gt; (string) Account-level: Jira project key to sync workloads to. Constraints: o min: 1 o max: 100 o pattern: [A-Z][A-Z0-9_]* IntegrationStatus -&gt; (string) Account-level: Configuration status of the Jira integration. Possible values: o NOT_CONFIGURED Shorthand Syntax: IssueManagementStatus=string,IssueManagementType=string,JiraProjectKey=string,IntegrationStatus=string JSON Syntax: { "IssueManagementStatus": "ENABLED"|"DISABLED", "IssueManagementType": "AUTO"|"MANUAL", "JiraProjectKey": "string", "IntegrationStatus": "NOT_CONFIGURED" }
    /// </summary>
    [CliOption("--jira-configuration")]
    public string? JiraConfiguration { get; set; }

    [CliFlag("--cli-input-json")]
    public bool? CliInputJson { get; set; }

    [CliFlag("--generate-cli-skeleton")]
    public bool? GenerateCliSkeleton { get; set; }

}
