<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratedOptionsAssembly>ModularPipelines.Yarn</GeneratedOptionsAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularPipelines.Yarn\ModularPipelines.Yarn.csproj" />
  </ItemGroup>
  <Import Project="..\GeneratedOptionsSmokeTests\GeneratedOptionsSmokeTests.props" />
</Project>
