// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Trivy.Options;

namespace ModularPipelines.Trivy.Options;

/// <summary>
/// [EXPERIMENTAL] VEX utilities
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("vex")]
public record TrivyVexOptions : TrivyOptions
{
    /// <summary>
    /// show version
    /// </summary>
    [CliFlag("--version", ShortForm = "-v")]
    public bool? Version { get; set; }

    /// <summary>
    /// The command operand.
    /// </summary>
    [CliArgument(0, Phase = CommandLinePhase.EarlyOperand)]
    public string? Command { get; set; }

}
