// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Kubernetes.Options;
using ModularPipelines.Kubernetes.Enums;

namespace ModularPipelines.Kubernetes.Options;

/// <summary>
/// View previous rollout revisions and configurations.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("rollout", "history")]
public record KubernetesRolloutHistoryOptions(
    [property: CliArgument(0, Phase = CommandLinePhase.EarlyOperand)] string TypeName
) : KubernetesOptions
{
    public KubernetesRolloutHistoryOptions()
        : this(default(string)!)
    {
    }

    /// <summary>
    /// If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to golang and jsonpath output formats.
    /// </summary>
    [CliOption("--allow-missing-template-keys", Format = OptionFormat.EqualsSeparated)]
    public bool? AllowMissingTemplateKeys { get; set; }

    /// <summary>
    /// Filename, directory, or URL to files identifying the resource to get from a server.
    /// </summary>
    [CliOption("--filename", ShortForm = "-f", Format = OptionFormat.EqualsSeparated)]
    public IEnumerable<string>? Filename { get; set; }

    /// <summary>
    /// Process the kustomization directory. This flag can't be used together with -f or -R.
    /// </summary>
    [CliOption("--kustomize", ShortForm = "-k", Format = OptionFormat.EqualsSeparated)]
    public string? Kustomize { get; set; }

    /// <summary>
    /// Output format. One of: (json, yaml, kyaml, name, go-template, go-template-file, template, templatefile, jsonpath, jsonpath-as-json, jsonpath-file).
    /// </summary>
    [CliOption("--output", ShortForm = "-o", Format = OptionFormat.EqualsSeparated)]
    public KubernetesRolloutHistoryOutput? Output { get; set; }

    /// <summary>
    /// Process the directory used in -f, --filename recursively. Useful when you want to manage related manifests organized within the same directory.
    /// </summary>
    [CliFlag("--recursive", ShortForm = "-R")]
    public bool? Recursive { get; set; }

    /// <summary>
    /// See the details, including podTemplate of the revision specified
    /// </summary>
    [CliOption("--revision", Format = OptionFormat.EqualsSeparated)]
    public int? Revision { get; set; }

    /// <summary>
    /// Selector (label query) to filter on, supports '=', '==', '!=', 'in', 'notin'.(e.g. -l key1=value1,key2=value2,key3 in (value3)). Matching objects must satisfy all of the specified label constraints.
    /// </summary>
    [CliOption("--selector", ShortForm = "-l", Format = OptionFormat.EqualsSeparated)]
    public string? Selector { get; set; }

    /// <summary>
    /// If true, keep the managedFields when printing objects in JSON or YAML format.
    /// </summary>
    [CliFlag("--show-managed-fields")]
    public bool? ShowManagedFields { get; set; }

    /// <summary>
    /// Template string or path to template file to use when -o=go-template, -o=go-template-file. The template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
    /// </summary>
    [CliOption("--template", Format = OptionFormat.EqualsSeparated)]
    public string? Template { get; set; }

}
