<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratedOptionsAssembly>ModularPipelines.Chocolatey</GeneratedOptionsAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularPipelines.Chocolatey\ModularPipelines.Chocolatey.csproj" />
  </ItemGroup>
  <Import Project="..\GeneratedOptionsSmokeTests\GeneratedOptionsSmokeTests.props" />
</Project>
