<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="ModularPipelines" Version="__MODULAR_PIPELINES_VERSION__" />
    <PackageVersion Include="ModularPipelines.DotNet" Version="__MODULAR_PIPELINES_VERSION__" />
  </ItemGroup>
</Project>
