// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Create a Batch application package record and activate it.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("batch", "application", "package", "create")]
public record AzBatchApplicationPackageCreateOptions(
    [property: CliOption("--application-name")] string ApplicationName,
    [property: CliOption("--name", ShortForm = "-n")] string Name,
    [property: CliOption("--package-file")] string PackageFile,
    [property: CliOption("--resource-group", ShortForm = "-g")] string ResourceGroup,
    [property: CliOption("--version-name")] string VersionName
) : AzOptions
{
}
