// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Restore a deleted table within the same account.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("cosmosdb", "table", "restore")]
public record AzCosmosdbTableRestoreOptions(
    [property: CliOption("--account-name", ShortForm = "-a")] string AccountName,
    [property: CliOption("--resource-group", ShortForm = "-g")] string ResourceGroup,
    [property: CliOption("--table-name", ShortForm = "-n")] string TableName
) : AzOptions
{
    public AzCosmosdbTableRestoreOptions()
        : this(default(string)!, default(string)!, default(string)!)
    {
    }

    /// <summary>
    /// Flag to restore with TTL disabled.
    /// </summary>
    [CliFlag("--disable-ttl")]
    public bool? DisableTtl { get; set; }

    /// <summary>
    /// The timestamp to which the Table needs to be restored to.
    /// </summary>
    [CliFlag("--restore-timestamp", ShortForm = "-t")]
    public bool? RestoreTimestamp { get; set; }

}
