// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Delete a function key.
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("functionapp", "function", "keys", "delete")]
public record AzFunctionappFunctionKeysDeleteOptions : AzOptions
{
    /// <summary>
    /// Name of the Function.
    /// </summary>
    [CliFlag("--function-name")]
    public bool? FunctionName { get; set; }

    /// <summary>
    /// The name of the slot. Defaults to the productions slot if not specified.
    /// </summary>
    [CliFlag("--slot", ShortForm = "-s")]
    public bool? Slot { get; set; }

}
