// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Create a connection monitor.
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("network", "watcher", "connection-monitor", "create")]
public record AzNetworkWatcherConnectionMonitorCreateOptions : AzOptions
{
    /// <summary>
    /// Location. Values from: `az account list- locations`. You can configure the default location using `az configure --defaults location=&lt;location&gt;`.
    /// </summary>
    [CliFlag("--location", ShortForm = "-l")]
    public bool? Location { get; set; }

    /// <summary>
    /// Do not wait for the long-running operation to finish.  Allowed values: 0, 1, f, false, n, no, t, true, y, yes.
    /// </summary>
    [CliFlag("--no-wait")]
    public bool? NoWait { get; set; }

    /// <summary>
    /// Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.
    /// </summary>
    [CliFlag("--resource-group", ShortForm = "-g")]
    public bool? ResourceGroup { get; set; }

    /// <summary>
    /// Space-separated tags: key[=value] [key[=value] ...]. Use ''to clear existing tags.  Support shorthand-syntax, json-file and yaml-file. Try "??" to show more.
    /// </summary>
    [CliFlag("--tags")]
    public bool? Tags { get; set; }

}
