// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// List address pools.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("network", "application-gateway", "address-pool", "list")]
public record AzNetworkApplicationGatewayAddressPoolListOptions(
    [property: CliOption("--gateway-name")] string GatewayName,
    [property: CliOption("--resource-group", ShortForm = "-g")] string ResourceGroup
) : AzOptions
{
}
