// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Create a VPN connection.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("network", "vpn-connection", "create")]
public record AzNetworkVpnConnectionCreateOptions : AzOptions
{
    /// <summary>
    /// Create a VPN connection.
    /// </summary>
    /// <param name="Name">Connection name.</param>
    /// <param name="ResourceGroup">Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.</param>
    /// <param name="VnetGateway1">Name or ID of the source virtual network gateway.</param>
    public AzNetworkVpnConnectionCreateOptions(
        string Name,
        string ResourceGroup,
        string VnetGateway1
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(Name);
        this.Name = Name;
        global::System.ArgumentNullException.ThrowIfNull(ResourceGroup);
        this.ResourceGroup = ResourceGroup;
        global::System.ArgumentNullException.ThrowIfNull(VnetGateway1);
        this.VnetGateway1 = VnetGateway1;
    }

    public void Deconstruct(out string Name, out string ResourceGroup, out string VnetGateway1)
    {
        Name = this.Name;
        ResourceGroup = this.ResourceGroup;
        VnetGateway1 = this.VnetGateway1;
    }

    /// <summary>
    /// Connection name.
    /// </summary>
    [CliOption("--name", ShortForm = "-n")]
    public string Name { get; private init; }

    /// <summary>
    /// Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.
    /// </summary>
    [CliOption("--resource-group", ShortForm = "-g")]
    public string ResourceGroup { get; private init; }

    /// <summary>
    /// Name or ID of the source virtual network gateway.
    /// </summary>
    [CliOption("--vnet-gateway1")]
    public string VnetGateway1 { get; private init; }

    /// <summary>
    /// Authentication type for the VPN connection.  Allowed values: Certificate, PSK.
    /// </summary>
    [CliOption("--auth-type", ShortForm = "--authentication-type")]
    public string? AuthType { get; set; }

    /// <summary>
    /// The authorization key for the VPN connection.
    /// </summary>
    [CliFlag("--authorization-key")]
    public bool? AuthorizationKey { get; set; }

    /// <summary>
    /// Certificate-based authentication configuration. Provide as JSON string or file path with @ prefix, Expected keys (outboundAuthCertificate, inboundAuthCertificateChain, inboundAuthCertificateSubjectName).
    /// </summary>
    [CliFlag("--cert-auth", ShortForm = "--certificate-authentication")]
    public bool? CertAuth { get; set; }

    /// <summary>
    /// Enable BGP for this VPN connection.
    /// </summary>
    [CliFlag("--enable-bgp")]
    public bool? EnableBgp { get; set; }

    /// <summary>
    /// Bypass ExpressRoute gateway for data forwarding. Allowed values: false, true.
    /// </summary>
    [CliOption("--express-route-gateway-bypass")]
    public bool? ExpressRouteGatewayBypass { get; set; }

    /// <summary>
    /// Location. Values from: `az account list-locations`. You can configure the default location using `az configure --defaults location=&lt;location&gt;`.
    /// </summary>
    [CliOption("--location", ShortForm = "-l")]
    public string? Location { get; set; }

    /// <summary>
    /// Connection routing weight.  Default: 10.
    /// </summary>
    [CliFlag("--routing-weight")]
    public bool? RoutingWeight { get; set; }

    /// <summary>
    /// Shared IPSec key.
    /// </summary>
    [CliFlag("--shared-key")]
    public bool? SharedKey { get; set; }

    /// <summary>
    /// Space-separated tags: key[=value] [key[=value] ...]. Use '' to clear existing tags.
    /// </summary>
    [CliOption("--tags", GroupValues = true)]
    public IEnumerable<string>? Tags { get; set; }

    /// <summary>
    /// Enable policy-based traffic selectors.  Allowed values: false, true.
    /// </summary>
    [CliOption("--use-policy-based-traffic-selectors")]
    public bool? UsePolicyBasedTrafficSelectors { get; set; }

    /// <summary>
    /// Display and validate the ARM template but do not create any resources.
    /// </summary>
    [CliFlag("--validate")]
    public bool? Validate { get; set; }

    /// <summary>
    /// Name or ID of the destination ExpressRoute to connect to using an 'ExpressRoute' connection.
    /// </summary>
    [CliOption("--express-route-circuit2")]
    public string? ExpressRouteCircuit2 { get; set; }

    /// <summary>
    /// Name or ID of the destination local network gateway to connect to using an 'IPSec' connection.
    /// </summary>
    [CliOption("--local-gateway2")]
    public string? LocalGateway2 { get; set; }

    /// <summary>
    /// Name or ID of the destination virtual network gateway to connect to using a 'Vnet2Vnet' connection.
    /// </summary>
    [CliOption("--vnet-gateway2")]
    public string? VnetGateway2 { get; set; }

}
