// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Create a new role assignment for a user, group, or service
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("role", "assignment", "create")]
public record AzRoleAssignmentCreateOptions : AzOptions
{
    /// <summary>
    /// Represent a user, group, or service principal. supported format: object id, user sign-in name, or service principal name.
    /// </summary>
    [CliFlag("--assignee")]
    public bool? Assignee { get; set; }

    /// <summary>
    /// The assignee's object ID (also known as principal ID). Use this argument instead of '--assignee' to bypass Microsoft Graph query in case the logged-in account has no permission or the machine has no network access to query Microsoft Graph.
    /// </summary>
    [CliFlag("--assignee-object-id")]
    public bool? AssigneeObjectId { get; set; }

    /// <summary>
    /// Use with --assignee-object-id to avoid errors caused by propagation latency in Microsoft Graph.  Allowed values: ForeignGroup, Group, ServicePrincipal, User.
    /// </summary>
    [CliFlag("--assignee-principal-type")]
    public bool? AssigneePrincipalType { get; set; }

    /// <summary>
    /// A GUID for the role assignment. It must be unique and different for each role assignment. If omitted, a new GUID is generated.
    /// </summary>
    [CliFlag("--name", ShortForm = "-n")]
    public bool? Name { get; set; }

}
