// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Create an self-hosted integration runtime.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("synapse", "integration-runtime", "self-hosted", "create")]
public record AzSynapseIntegrationRuntimeSelfHostedCreateOptions(
    [property: CliOption("--name", ShortForm = "-n")] string Name,
    [property: CliOption("--resource-group", ShortForm = "-g")] string ResourceGroup,
    [property: CliOption("--workspace-name")] string WorkspaceName
) : AzOptions
{
    public AzSynapseIntegrationRuntimeSelfHostedCreateOptions()
        : this(default(string)!, default(string)!, default(string)!)
    {
    }

    /// <summary>
    /// The integration runtime description.
    /// </summary>
    [CliFlag("--description")]
    public bool? Description { get; set; }

    /// <summary>
    /// ETag of the integration runtime entity. Should only be specified for update, for which it should match existing entity or can be * for unconditional update.
    /// </summary>
    [CliFlag("--if-match")]
    public bool? IfMatch { get; set; }

    /// <summary>
    /// Do not wait for the long-running operation to finish.
    /// </summary>
    [CliFlag("--no-wait")]
    public bool? NoWait { get; set; }

}
