// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Options;

/// <summary>
/// Manage auto-shutdown for VM.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("vm", "auto-shutdown")]
public record AzVmAutoShutdownOptions : AzOptions
{
    /// <summary>
    /// The email recipient to send notifications to (can be a list of semi- colon separated email addresses).
    /// </summary>
    [CliFlag("--email")]
    public bool? Email { get; set; }

    /// <summary>
    /// Location. Values from: `az account list-locations`. You can configure the default location using `az configure --defaults location=&lt;location&gt;`.
    /// </summary>
    [CliFlag("--location", ShortForm = "-l")]
    public bool? Location { get; set; }

    /// <summary>
    /// Turn off auto-shutdown for VM. Configuration will be cleared.
    /// </summary>
    [CliFlag("--off")]
    public bool? Off { get; set; }

    /// <summary>
    /// The UTC time of day the schedule will occur every day. Format: hhmm.
    /// </summary>
    [CliFlag("--time")]
    public bool? Time { get; set; }

    /// <summary>
    /// The webhook URL to which the notification will be sent.
    /// </summary>
    [CliFlag("--webhook")]
    public bool? Webhook { get; set; }

    /// <summary>
    /// One or more resource IDs (space-delimited). It should be a complete resource ID containing all information of 'Resource Id' arguments. You should provide either --ids or other 'Resource Id' arguments.
    /// </summary>
    [CliOption("--ids", GroupValues = true)]
    public IEnumerable<string>? Ids { get; set; }

    /// <summary>
    /// The name of the Virtual Machine. You can configure the default using `az configure --defaults vm=&lt;name&gt;`.
    /// </summary>
    [CliOption("--name", ShortForm = "-n")]
    public string? Name { get; set; }

    /// <summary>
    /// Name of resource group. You can configure the default group using `az configure --defaults group=&lt;name&gt;`.
    /// </summary>
    [CliOption("--resource-group", ShortForm = "-g")]
    public string? ResourceGroup { get; set; }

}
