// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Do not edit this file manually.
// </auto-generated>

using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Services;

/// <summary>
/// az container commands.
/// </summary>
public class AzDataboxedgeDeviceStorageAccountContainer
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="AzDataboxedgeDeviceStorageAccountContainer"/> class.
    /// </summary>
    public AzDataboxedgeDeviceStorageAccountContainer(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// Create container on the device.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Create(
        AzDataboxedgeDeviceStorageAccountContainerCreateOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    /// <summary>
    /// Delete the container on the Data Box
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Delete(
        AzDataboxedgeDeviceStorageAccountContainerDeleteOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    /// <summary>
    /// Update container on the device.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Update(
        AzDataboxedgeDeviceStorageAccountContainerUpdateOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    #endregion
}
