// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2026-01-03.
// Do not edit this file manually.
// </auto-generated>

using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Services;

/// <summary>
/// az extension commands.
/// </summary>
public class AzExtension
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="AzExtension"/> class.
    /// </summary>
    public AzExtension(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// Add an extension.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Add(
        AzExtensionAddOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new AzExtensionAddOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// List publicly available extensions.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListAvailable(
        AzExtensionListAvailableOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new AzExtensionListAvailableOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Update an extension.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Update(
        AzExtensionUpdateOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new AzExtensionUpdateOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
