// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Services;

/// <summary>
/// az policy commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "1.0.0")]
public class AzNetworkServiceEndpointPolicy
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="AzNetworkServiceEndpointPolicy"/> class.
    /// </summary>
    public AzNetworkServiceEndpointPolicy(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// Create a service endpoint policy.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Create(
        AzNetworkServiceEndpointPolicyCreateOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new AzNetworkServiceEndpointPolicyCreateOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Delete a service endpoint policy.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Delete(
        AzNetworkServiceEndpointPolicyDeleteOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new AzNetworkServiceEndpointPolicyDeleteOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// List service endpoint policies.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> List(
        AzNetworkServiceEndpointPolicyListOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new AzNetworkServiceEndpointPolicyListOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Update a service endpoint policy.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Update(
        AzNetworkServiceEndpointPolicyUpdateOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new AzNetworkServiceEndpointPolicyUpdateOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
