// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Do not edit this file manually.
// </auto-generated>

using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Services;

/// <summary>
/// az rule commands.
/// </summary>
public class AzStorageAccountOrPolicyRule
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="AzStorageAccountOrPolicyRule"/> class.
    /// </summary>
    public AzStorageAccountOrPolicyRule(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// Add rule to the specified Object Replication Service
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Add(
        AzStorageAccountOrPolicyRuleAddOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    /// <summary>
    /// List all the rules in the specified Object Replication
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> List(
        AzStorageAccountOrPolicyRuleListOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    /// <summary>
    /// Remove the specified rule from the specified Object
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Remove(
        AzStorageAccountOrPolicyRuleRemoveOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    /// <summary>
    /// Show the properties of specified rule in Object
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Show(
        AzStorageAccountOrPolicyRuleShowOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    /// <summary>
    /// Update rule properties to Object Replication Service
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Update(
        AzStorageAccountOrPolicyRuleUpdateOptions options,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, cancellationToken);
    }

    #endregion
}
