// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Context.Domains.Shell;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Azure.Options;

namespace ModularPipelines.Azure.Services;

/// <summary>
/// az connection-string commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public class AzWebappConfigConnectionString
{
    private readonly ICommandContext _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="AzWebappConfigConnectionString"/> class.
    /// </summary>
    public AzWebappConfigConnectionString(ICommandContext command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// Delete a web app's connection strings.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteAsync(
        AzWebappConfigConnectionStringDeleteOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// Get a web app's connection strings.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListAsync(
        AzWebappConfigConnectionStringListOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// Update a web app's connection strings.
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetAsync(
        AzWebappConfigConnectionStringSetOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AzWebappConfigConnectionStringSetOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
