<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularPipelines.SourceGenerator\ModularPipelines.SourceGenerator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Snapshots\**\*.verified.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
