<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratedOptionsAssembly>ModularPipelines.DotNet</GeneratedOptionsAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularPipelines.DotNet\ModularPipelines.DotNet.csproj" />
    <ProjectReference Include="..\ModularPipelines.DocumentationSnippets\ModularPipelines.DocumentationSnippets.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\ModularPipelines.TestsForTests\ModularPipelines.TestsForTests.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>
  <Import Project="..\GeneratedOptionsSmokeTests\GeneratedOptionsSmokeTests.props" />
</Project>
