<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratedOptionsAssembly>ModularPipelines.Vault</GeneratedOptionsAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularPipelines.Vault\ModularPipelines.Vault.csproj" />
  </ItemGroup>
  <Import Project="..\GeneratedOptionsSmokeTests\GeneratedOptionsSmokeTests.props" />
</Project>
