<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Templates for creating realistic ModularPipelines build, test, and publish pipelines.</Description>
    <PackageType>Template</PackageType>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <Title>ModularPipelines project templates</Title>
    <PackageTags>dotnet-new;templates;build;test;publish;pipelines</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="templates\**\*" Exclude="templates\**\bin\**;templates\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>
</Project>
