<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratedOptionsAssembly>ModularPipelines.Helm</GeneratedOptionsAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularPipelines.Helm\ModularPipelines.Helm.csproj" />
  </ItemGroup>
  <Import Project="..\GeneratedOptionsSmokeTests\GeneratedOptionsSmokeTests.props" />
</Project>
