// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Services;

/// <summary>
/// aws lambdaweb commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public class AwsLambdaWeb : IAwsLambdaWeb
{
    private readonly ICommandContext _command;
    private AwsLambdaWebWait? _wait;

    /// <summary>
    /// Initializes a new instance of the <see cref="AwsLambdaWeb"/> class.
    /// </summary>
    public AwsLambdaWeb(ICommandContext command)
    {
        _command = command;
    }

    #region Sub-command Groups

    /// <summary>
    /// aws wait sub-commands.
    /// </summary>
    public AwsLambdaWebWait Wait => _wait ??= new AwsLambdaWebWait(_command);

    #endregion

    #region Commands

    /// <summary>
    /// Creates an endpoint for a web function. An endpoint exposes the web function over HTTPS and routes traffic to one or more revisions. To use this operation, you must have the CreateWebFunctionEndpoint per- mission on the web function, not on the endpoint being created. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> CreateWebFunctionEndpointAsync(
        AwsLambdaWebCreateWebFunctionEndpointOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Creates a web function with an initial revision and endpoint. To create a web function, you provide the function name, revision configuration (code and service settings), and endpoint configuration. To use this operation, you must have the CreateWebFunction permission on the web function. You don't need separate permissions for the ini- tial revision or endpoint. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documen...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> CreateWebFunctionAsync(
        AwsLambdaWebCreateWebFunctionOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Creates an immutable revision for a web function. A revision represents a specific version of the function code and configuration. To use this operation, you must have the CreateWebFunctionRevision per- mission on the web function, not on the revision being created. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> CreateWebFunctionRevisionAsync(
        AwsLambdaWebCreateWebFunctionRevisionOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Removes the resource-based policy from a web function. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteResourcePolicyAsync(
        AwsLambdaWebDeleteResourcePolicyOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Deletes a web function endpoint. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteWebFunctionEndpointAsync(
        AwsLambdaWebDeleteWebFunctionEndpointOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Deletes a web function and all of its associated revisions and end- points. To use this operation, you must have the DeleteWebFunction permission on the web function. You don't need the DeleteWebFunctionRevision or DeleteWebFunctionEndpoint permission. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteWebFunctionAsync(
        AwsLambdaWebDeleteWebFunctionOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Deletes a web function revision. You cannot delete a revision that is currently serving traffic on an endpoint. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteWebFunctionRevisionAsync(
        AwsLambdaWebDeleteWebFunctionRevisionOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Deploys a local HTTP server to an AWS Lambda Web Function. The command creates a Web Function or deploys a new revision to an existing Web Function, applies the requested endpoint configuration, and returns the endpoint URL. The deploy command coordinates API operations for common create and up- date workflows. For configuration that is not available through deploy, such as weighted revision routing or connecting a Web Function to a VPC, use the aws lambda-web commands for specific API operation...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeployAsync(
        AwsLambdaWebDeployOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Retrieves the resource-based policy attached to a web function. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetResourcePolicyAsync(
        AwsLambdaWebGetResourcePolicyOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Retrieves details about your AWS Lambda Web Functions account settings for the current AWS Region, including the quotas that apply to web functions and your current usage. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetWebAccountSettingsAsync(
        AwsLambdaWebGetWebAccountSettingsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsLambdaWebGetWebAccountSettingsOptions(), executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Retrieves details about a web function endpoint, including its current state, configuration, and domain name. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetWebFunctionEndpointAsync(
        AwsLambdaWebGetWebFunctionEndpointOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Retrieves details about a web function, including its current state and configuration. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetWebFunctionAsync(
        AwsLambdaWebGetWebFunctionOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Retrieves details about a web function revision, including its state and configuration. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetWebFunctionRevisionAsync(
        AwsLambdaWebGetWebFunctionRevisionOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Returns a list of tags applied to a web function. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListTagsAsync(
        AwsLambdaWebListTagsOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Lists endpoints for a web function. We recommend using pagination to ensure that the operation returns quickly and successfully. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation list-web-function-endpoints is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of re- sults. You can disable pagination by providing the --no-paginate argu- ment. When using --outpu...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListWebFunctionEndpointsAsync(
        AwsLambdaWebListWebFunctionEndpointsOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Lists revisions for a web function. We recommend using pagination to ensure that the operation returns quickly and successfully. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation list-web-function-revisions is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of re- sults. You can disable pagination by providing the --no-paginate argu- ment. When using --outpu...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListWebFunctionRevisionsAsync(
        AwsLambdaWebListWebFunctionRevisionsOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Lists web functions in your account. We recommend using pagination to ensure that the operation returns quickly and successfully. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation list-web-functions is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results. You can disable pagination by providing the --no-paginate argument. When using --output text and t...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListWebFunctionsAsync(
        AwsLambdaWebListWebFunctionsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsLambdaWebListWebFunctionsOptions(), executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Adds or updates a resource-based policy on a web function. A re- source-based policy grants permissions to other AWS accounts or ser- vices to perform actions on the web function. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> PutResourcePolicyAsync(
        AwsLambdaWebPutResourcePolicyOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Adds tags to a web function. If a tag key already exists, the existing value is overwritten with the new value. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> TagResourceAsync(
        AwsLambdaWebTagResourceOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Removes tags from a web function. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UntagResourceAsync(
        AwsLambdaWebUntagResourceOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Updates the configuration of a web function endpoint. You can modify the authorization type, auto-deployment mode, revision weights, scal- ing, and throttling settings. NOTE: This API is experimental and for internal AWS use only. It is not yet available to external customers. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateWebFunctionEndpointAsync(
        AwsLambdaWebUpdateWebFunctionEndpointOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken).ConfigureAwait(false);
    }

    #endregion
}
