// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Context.Domains.Shell;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.AmazonWebServices.Options;

namespace ModularPipelines.AmazonWebServices.Services;

/// <summary>
/// aws ssmsap commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public class AwsSsmSap : IAwsSsmSap
{
    private readonly ICommandContext _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="AwsSsmSap"/> class.
    /// </summary>
    public AwsSsmSap(ICommandContext command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// Removes permissions associated with the target database. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteResourcePermissionAsync(
        AwsSsmSapDeleteResourcePermissionOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapDeleteResourcePermissionOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Deregister an SAP application with AWS Systems Manager for SAP. This action does not aect the existing setup of your SAP workloads on Amazon EC2. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeregisterApplicationAsync(
        AwsSsmSapDeregisterApplicationOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapDeregisterApplicationOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Gets an application registered with AWS Systems Manager for SAP. It also returns the components of the application. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetApplicationAsync(
        AwsSsmSapGetApplicationOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapGetApplicationOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Gets the component of an application registered with AWS Systems Man- ager for SAP. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetComponentAsync(
        AwsSsmSapGetComponentOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapGetComponentOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Gets the details of a configuration check operation by specifying the operation ID. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetConfigurationCheckOperationAsync(
        AwsSsmSapGetConfigurationCheckOperationOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapGetConfigurationCheckOperationOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Gets the SAP HANA database of an application registered with AWS Sys- tems Manager for SAP. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetDatabaseAsync(
        AwsSsmSapGetDatabaseOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapGetDatabaseOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Gets the details of an operation by specifying the operation ID. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetOperationAsync(
        AwsSsmSapGetOperationOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapGetOperationOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Gets permissions associated with the target database. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetResourcePermissionAsync(
        AwsSsmSapGetResourcePermissionOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapGetResourcePermissionOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists all the applications registered with AWS Systems Manager for SAP. See also: AWS API Documentation list-applications is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results. You can disable pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressions: Applications
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListApplicationsAsync(
        AwsSsmSapListApplicationsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListApplicationsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists all the components registered with AWS Systems Manager for SAP. See also: AWS API Documentation list-components is a paginated operation. Multiple API calls may be is- sued in order to retrieve the entire data set of results. You can dis- able pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressions: Components
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListComponentsAsync(
        AwsSsmSapListComponentsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListComponentsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists all configuration check types supported by AWS Systems Manager for SAP. See also: AWS API Documentation list-configuration-check-definitions is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of re- sults. You can disable pagination by providing the --no-paginate argu- ment. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressions: Co...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListConfigurationCheckDefinitionsAsync(
        AwsSsmSapListConfigurationCheckDefinitionsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListConfigurationCheckDefinitionsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists the configuration check operations performed by AWS Systems Man- ager for SAP. See also: AWS API Documentation list-configuration-check-operations is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of re- sults. You can disable pagination by providing the --no-paginate argu- ment. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressio...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListConfigurationCheckOperationsAsync(
        AwsSsmSapListConfigurationCheckOperationsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListConfigurationCheckOperationsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists the SAP HANA databases of an application registered with AWS Sys- tems Manager for SAP. See also: AWS API Documentation list-databases is a paginated operation. Multiple API calls may be is- sued in order to retrieve the entire data set of results. You can dis- able pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressions: Database...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListDatabasesAsync(
        AwsSsmSapListDatabasesOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListDatabasesOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Returns a list of operations events. Available parameters include OperationID , as well as optional parame- ters MaxResults , NextToken , and Filters . See also: AWS API Documentation list-operation-events is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results. You can disable pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --query argument must extract data ...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListOperationEventsAsync(
        AwsSsmSapListOperationEventsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListOperationEventsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists the operations performed by AWS Systems Manager for SAP. See also: AWS API Documentation list-operations is a paginated operation. Multiple API calls may be is- sued in order to retrieve the entire data set of results. You can dis- able pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressions: Operations
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListOperationsAsync(
        AwsSsmSapListOperationsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListOperationsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists the sub-check results of a specified configuration check opera- tion. See also: AWS API Documentation list-sub-check-results is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of results. You can disable pagination by providing the --no-paginate argument. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressions: SubCheckResults
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListSubCheckResultsAsync(
        AwsSsmSapListSubCheckResultsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListSubCheckResultsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists the rules of a specified sub-check belonging to a configuration check operation. See also: AWS API Documentation list-sub-check-rule-results is a paginated operation. Multiple API calls may be issued in order to retrieve the entire data set of re- sults. You can disable pagination by providing the --no-paginate argu- ment. When using --output text and the --query argument on a paginated response, the --query argument must extract data from the results of the following query expressions: Ru...
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListSubCheckRuleResultsAsync(
        AwsSsmSapListSubCheckRuleResultsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListSubCheckRuleResultsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Lists all tags on an SAP HANA application and/or database registered with AWS Systems Manager for SAP. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListTagsForResourceAsync(
        AwsSsmSapListTagsForResourceOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapListTagsForResourceOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Adds permissions to the target database. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> PutResourcePermissionAsync(
        AwsSsmSapPutResourcePermissionOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapPutResourcePermissionOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Register an SAP application with AWS Systems Manager for SAP. You must meet the following requirements before registering. The SAP application you want to register with AWS Systems Manager for SAP is running on Amazon EC2. AWS Systems Manager Agent must be setup on an Amazon EC2 instance along with the required IAM permissions. Amazon EC2 instance(s) must have access to the secrets created in AWS Secrets Manager to manage SAP applications and components. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RegisterApplicationAsync(
        AwsSsmSapRegisterApplicationOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapRegisterApplicationOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Request is an operation which starts an application. Parameter ApplicationId is required. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> StartApplicationAsync(
        AwsSsmSapStartApplicationOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapStartApplicationOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Refreshes a registered application. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> StartApplicationRefreshAsync(
        AwsSsmSapStartApplicationRefreshOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapStartApplicationRefreshOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Initiates configuration check operations against a specified applica- tion. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> StartConfigurationChecksAsync(
        AwsSsmSapStartConfigurationChecksOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapStartConfigurationChecksOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Request is an operation to stop an application. Parameter ApplicationId is required. Parameters StopConnectedEntity and IncludeEc2InstanceShutdown are optional. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> StopApplicationAsync(
        AwsSsmSapStopApplicationOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapStopApplicationOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Creates tag for a resource by specifying the ARN. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> TagResourceAsync(
        AwsSsmSapTagResourceOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapTagResourceOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Delete the tags for a resource. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UntagResourceAsync(
        AwsSsmSapUntagResourceOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapUntagResourceOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// Updates the settings of an application registered with AWS Systems Man- ager for SAP. See also: AWS API Documentation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateApplicationSettingsAsync(
        AwsSsmSapUpdateApplicationSettingsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new AwsSsmSapUpdateApplicationSettingsOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
