// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Attributes;

namespace ModularPipelines.Google.Enums;

/// <summary>
/// Allowed values for --ipversion.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public enum GcloudIpVersion
{
    [EnumValue("IPV4")]
    Ipv4 = 0,

    [EnumValue("IPV6")]
    Ipv6 = 1
}
