// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Terraform.Options;

namespace ModularPipelines.Terraform.Options;

/// <summary>
/// Create or update the dependency lock file (.terraform.lock.hcl) for the
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.42.227-alpha.0.981+55c59948e83059a5184db05c992047e177e72c4b")]
[ExcludeFromCodeCoverage]
[CliSubCommand("stacks", "providers-lock")]
public record TerraformStacksProvidersLockOptions : TerraformOptions
{
}
