// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud operations commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "")]
public class GcloudIamWorkforcePoolsOperations
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudIamWorkforcePoolsOperations"/> class.
    /// </summary>
    public GcloudIamWorkforcePoolsOperations(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// describe a workforce pool     operation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Describe(
        GcloudIamWorkforcePoolsOperationsDescribeOptions options = default,
        CommandExecutionOptions executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudIamWorkforcePoolsOperationsDescribeOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
