// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud runtimes commands.
/// </summary>
public class GcloudNotebooksRuntimes
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudNotebooksRuntimes"/> class.
    /// </summary>
    public GcloudNotebooksRuntimes(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// request for creating an runtime
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Create(
        GcloudNotebooksRuntimesCreateOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesCreateOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for deleting runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Delete(
        GcloudNotebooksRuntimesDeleteOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesDeleteOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for describing runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Describe(
        GcloudNotebooksRuntimesDescribeOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesDescribeOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for diagnose runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Diagnose(
        GcloudNotebooksRuntimesDiagnoseOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesDiagnoseOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for listing runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> List(
        GcloudNotebooksRuntimesListOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesListOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for migrating runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Migrate(
        GcloudNotebooksRuntimesMigrateOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesMigrateOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for resetting runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Reset(
        GcloudNotebooksRuntimesResetOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesResetOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for starting runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Start(
        GcloudNotebooksRuntimesStartOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesStartOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for stopping runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Stop(
        GcloudNotebooksRuntimesStopOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesStopOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// request for switching runtimes
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Switch(
        GcloudNotebooksRuntimesSwitchOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudNotebooksRuntimesSwitchOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
