// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud operations commands.
/// </summary>
public class GcloudDatabasemigrationOperations
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudDatabasemigrationOperations"/> class.
    /// </summary>
    public GcloudDatabasemigrationOperations(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// delete a Database Migration     Service operation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Delete(
        GcloudDatabaseMigrationOperationsDeleteOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudDatabaseMigrationOperationsDeleteOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// show details about a     operation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Describe(
        GcloudDatabaseMigrationOperationsDescribeOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudDatabaseMigrationOperationsDescribeOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// list operations
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> List(
        GcloudDatabaseMigrationOperationsListOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudDatabaseMigrationOperationsListOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
