// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-23.
// Do not edit this file manually.
// </auto-generated>

using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud instances commands.
/// </summary>
public class GcloudComputeInstances
{
    private readonly ICommand _command;
    private GcloudComputeInstancesBulk? _bulk;
    private GcloudComputeInstancesNetworkInterfaces? _networkInterfaces;
    private GcloudComputeInstancesOpsAgents? _opsAgents;
    private GcloudComputeInstancesOsInventory? _osInventory;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudComputeInstances"/> class.
    /// </summary>
    public GcloudComputeInstances(ICommand command)
    {
        _command = command;
    }

    #region Sub-command Groups

    /// <summary>
    /// gcloud bulk sub-commands.
    /// </summary>
    public GcloudComputeInstancesBulk Bulk => _bulk ??= new GcloudComputeInstancesBulk(_command);

    /// <summary>
    /// gcloud network-interfaces sub-commands.
    /// </summary>
    public GcloudComputeInstancesNetworkInterfaces NetworkInterfaces => _networkInterfaces ??= new GcloudComputeInstancesNetworkInterfaces(_command);

    /// <summary>
    /// gcloud ops-agents sub-commands.
    /// </summary>
    public GcloudComputeInstancesOpsAgents OpsAgents => _opsAgents ??= new GcloudComputeInstancesOpsAgents(_command);

    /// <summary>
    /// gcloud os-inventory sub-commands.
    /// </summary>
    public GcloudComputeInstancesOsInventory OsInventory => _osInventory ??= new GcloudComputeInstancesOsInventory(_command);

    #endregion

    #region Commands

    /// <summary>
    /// create a Compute Engine      virtual machine access configuration
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddAccessConfig(
        GcloudComputeInstancesAddAccessConfigOptions options,
        CancellationToken cancellationToken = default)
    {
        return await AddAccessConfig(options, null, cancellationToken);
    }

    /// <summary>
    /// create a Compute Engine      virtual machine access configuration
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddAccessConfig(
        GcloudComputeInstancesAddAccessConfigOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// add IAM policy binding to      a Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddIamPolicyBinding(
        GcloudComputeInstancesAddIamPolicyBindingOptions options,
        CancellationToken cancellationToken = default)
    {
        return await AddIamPolicyBinding(options, null, cancellationToken);
    }

    /// <summary>
    /// add IAM policy binding to      a Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddIamPolicyBinding(
        GcloudComputeInstancesAddIamPolicyBindingOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// add labels to Google Compute Engine      virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddLabels(
        GcloudComputeInstancesAddLabelsOptions options,
        CancellationToken cancellationToken = default)
    {
        return await AddLabels(options, null, cancellationToken);
    }

    /// <summary>
    /// add labels to Google Compute Engine      virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddLabels(
        GcloudComputeInstancesAddLabelsOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// add or update instance metadata
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddMetadata(
        GcloudComputeInstancesAddMetadataOptions options,
        CancellationToken cancellationToken = default)
    {
        return await AddMetadata(options, null, cancellationToken);
    }

    /// <summary>
    /// add or update instance metadata
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddMetadata(
        GcloudComputeInstancesAddMetadataOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// add resource policies to      Compute Engine VM instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddResourcePolicies(
        GcloudComputeInstancesAddResourcePoliciesOptions options,
        CancellationToken cancellationToken = default)
    {
        return await AddResourcePolicies(options, null, cancellationToken);
    }

    /// <summary>
    /// add resource policies to      Compute Engine VM instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddResourcePolicies(
        GcloudComputeInstancesAddResourcePoliciesOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// add tags to Compute Engine virtual      machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddTags(
        GcloudComputeInstancesAddTagsOptions options,
        CancellationToken cancellationToken = default)
    {
        return await AddTags(options, null, cancellationToken);
    }

    /// <summary>
    /// add tags to Compute Engine virtual      machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddTags(
        GcloudComputeInstancesAddTagsOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// attach a disk to an instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AttachDisk(
        GcloudComputeInstancesAttachDiskOptions options,
        CancellationToken cancellationToken = default)
    {
        return await AttachDisk(options, null, cancellationToken);
    }

    /// <summary>
    /// attach a disk to an instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AttachDisk(
        GcloudComputeInstancesAttachDiskOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// create Compute Engine virtual machine      instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Create(
        GcloudComputeInstancesCreateOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Create(options, null, cancellationToken);
    }

    /// <summary>
    /// create Compute Engine virtual machine      instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Create(
        GcloudComputeInstancesCreateOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// creates Compute Engine      virtual machine instances running container images
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> CreateWithContainer(
        GcloudComputeInstancesCreateWithContainerOptions options,
        CancellationToken cancellationToken = default)
    {
        return await CreateWithContainer(options, null, cancellationToken);
    }

    /// <summary>
    /// creates Compute Engine      virtual machine instances running container images
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> CreateWithContainer(
        GcloudComputeInstancesCreateWithContainerOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// delete an access      configuration from a virtual machine network interface
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteAccessConfig(
        GcloudComputeInstancesDeleteAccessConfigOptions options,
        CancellationToken cancellationToken = default)
    {
        return await DeleteAccessConfig(options, null, cancellationToken);
    }

    /// <summary>
    /// delete an access      configuration from a virtual machine network interface
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteAccessConfig(
        GcloudComputeInstancesDeleteAccessConfigOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// delete Compute Engine virtual machine      instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Delete(
        GcloudComputeInstancesDeleteOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Delete(options, null, cancellationToken);
    }

    /// <summary>
    /// delete Compute Engine virtual machine      instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Delete(
        GcloudComputeInstancesDeleteOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// describe a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Describe(
        GcloudComputeInstancesDescribeOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Describe(options, null, cancellationToken);
    }

    /// <summary>
    /// describe a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Describe(
        GcloudComputeInstancesDescribeOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// detach disks from Compute Engine      virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DetachDisk(
        GcloudComputeInstancesDetachDiskOptions options,
        CancellationToken cancellationToken = default)
    {
        return await DetachDisk(options, null, cancellationToken);
    }

    /// <summary>
    /// detach disks from Compute Engine      virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DetachDisk(
        GcloudComputeInstancesDetachDiskOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// export a Compute Engine virtual machine      instance's configuration to a file
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Export(
        GcloudComputeInstancesExportOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Export(options, null, cancellationToken);
    }

    /// <summary>
    /// export a Compute Engine virtual machine      instance's configuration to a file
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Export(
        GcloudComputeInstancesExportOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// get the Guest Attributes      for a compute instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetGuestAttributes(
        GcloudComputeInstancesGetGuestAttributesOptions options,
        CancellationToken cancellationToken = default)
    {
        return await GetGuestAttributes(options, null, cancellationToken);
    }

    /// <summary>
    /// get the Guest Attributes      for a compute instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetGuestAttributes(
        GcloudComputeInstancesGetGuestAttributesOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// get the IAM policy for a Compute      Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetIamPolicy(
        GcloudComputeInstancesGetIamPolicyOptions options,
        CancellationToken cancellationToken = default)
    {
        return await GetIamPolicy(options, null, cancellationToken);
    }

    /// <summary>
    /// get the IAM policy for a Compute      Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetIamPolicy(
        GcloudComputeInstancesGetIamPolicyOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// capture a screenshot (JPEG image)      of the virtual machine instance's display
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetScreenshot(
        GcloudComputeInstancesGetScreenshotOptions options,
        CancellationToken cancellationToken = default)
    {
        return await GetScreenshot(options, null, cancellationToken);
    }

    /// <summary>
    /// capture a screenshot (JPEG image)      of the virtual machine instance's display
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetScreenshot(
        GcloudComputeInstancesGetScreenshotOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// read output from a      virtual machine instance's serial port
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetSerialPortOutput(
        GcloudComputeInstancesGetSerialPortOutputOptions options,
        CancellationToken cancellationToken = default)
    {
        return await GetSerialPortOutput(options, null, cancellationToken);
    }

    /// <summary>
    /// read output from a      virtual machine instance's serial port
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetSerialPortOutput(
        GcloudComputeInstancesGetSerialPortOutputOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// get the Shielded identity      for a Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetShieldedIdentity(
        GcloudComputeInstancesGetShieldedIdentityOptions options,
        CancellationToken cancellationToken = default)
    {
        return await GetShieldedIdentity(options, null, cancellationToken);
    }

    /// <summary>
    /// get the Shielded identity      for a Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetShieldedIdentity(
        GcloudComputeInstancesGetShieldedIdentityOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// create Compute Engine virtual machine      instances from virtual appliance in OVA/OVF format
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Import(
        GcloudComputeInstancesImportOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Import(options, null, cancellationToken);
    }

    /// <summary>
    /// create Compute Engine virtual machine      instances from virtual appliance in OVA/OVF format
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Import(
        GcloudComputeInstancesImportOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// list Compute Engine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> List(
        GcloudComputeInstancesListOptions options,
        CancellationToken cancellationToken = default)
    {
        return await List(options, null, cancellationToken);
    }

    /// <summary>
    /// list Compute Engine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> List(
        GcloudComputeInstancesListOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// perform maintenance of      Google Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> PerformMaintenance(
        GcloudComputeInstancesPerformMaintenanceOptions options,
        CancellationToken cancellationToken = default)
    {
        return await PerformMaintenance(options, null, cancellationToken);
    }

    /// <summary>
    /// perform maintenance of      Google Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> PerformMaintenance(
        GcloudComputeInstancesPerformMaintenanceOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// remove IAM policy      binding from a Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveIamPolicyBinding(
        GcloudComputeInstancesRemoveIamPolicyBindingOptions options,
        CancellationToken cancellationToken = default)
    {
        return await RemoveIamPolicyBinding(options, null, cancellationToken);
    }

    /// <summary>
    /// remove IAM policy      binding from a Compute Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveIamPolicyBinding(
        GcloudComputeInstancesRemoveIamPolicyBindingOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// remove labels from Google Compute      Engine virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveLabels(
        GcloudComputeInstancesRemoveLabelsOptions options,
        CancellationToken cancellationToken = default)
    {
        return await RemoveLabels(options, null, cancellationToken);
    }

    /// <summary>
    /// remove labels from Google Compute      Engine virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveLabels(
        GcloudComputeInstancesRemoveLabelsOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// remove instance metadata
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveMetadata(
        GcloudComputeInstancesRemoveMetadataOptions options,
        CancellationToken cancellationToken = default)
    {
        return await RemoveMetadata(options, null, cancellationToken);
    }

    /// <summary>
    /// remove instance metadata
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveMetadata(
        GcloudComputeInstancesRemoveMetadataOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// remove resource      policies from Compute Engine VM instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveResourcePolicies(
        GcloudComputeInstancesRemoveResourcePoliciesOptions options,
        CancellationToken cancellationToken = default)
    {
        return await RemoveResourcePolicies(options, null, cancellationToken);
    }

    /// <summary>
    /// remove resource      policies from Compute Engine VM instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveResourcePolicies(
        GcloudComputeInstancesRemoveResourcePoliciesOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// remove tags from Compute Engine      virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveTags(
        GcloudComputeInstancesRemoveTagsOptions options,
        CancellationToken cancellationToken = default)
    {
        return await RemoveTags(options, null, cancellationToken);
    }

    /// <summary>
    /// remove tags from Compute Engine      virtual machine instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveTags(
        GcloudComputeInstancesRemoveTagsOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// report a host as faulty to      start the repair process
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ReportHostAsFaulty(
        GcloudComputeInstancesReportHostAsFaultyOptions options,
        CancellationToken cancellationToken = default)
    {
        return await ReportHostAsFaulty(options, null, cancellationToken);
    }

    /// <summary>
    /// report a host as faulty to      start the repair process
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ReportHostAsFaulty(
        GcloudComputeInstancesReportHostAsFaultyOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// reset a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Reset(
        GcloudComputeInstancesResetOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Reset(options, null, cancellationToken);
    }

    /// <summary>
    /// reset a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Reset(
        GcloudComputeInstancesResetOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// resume a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Resume(
        GcloudComputeInstancesResumeOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Resume(options, null, cancellationToken);
    }

    /// <summary>
    /// resume a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Resume(
        GcloudComputeInstancesResumeOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// send a diagnostic      interrupt to a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SendDiagnosticInterrupt(
        GcloudComputeInstancesSendDiagnosticInterruptOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SendDiagnosticInterrupt(options, null, cancellationToken);
    }

    /// <summary>
    /// send a diagnostic      interrupt to a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SendDiagnosticInterrupt(
        GcloudComputeInstancesSendDiagnosticInterruptOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// delete behavior      for disks
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetDiskAutoDelete(
        GcloudComputeInstancesSetDiskAutoDeleteOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SetDiskAutoDelete(options, null, cancellationToken);
    }

    /// <summary>
    /// delete behavior      for disks
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetDiskAutoDelete(
        GcloudComputeInstancesSetDiskAutoDeleteOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// set IAM policy for a Compute      Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetIamPolicy(
        GcloudComputeInstancesSetIamPolicyOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SetIamPolicy(options, null, cancellationToken);
    }

    /// <summary>
    /// set IAM policy for a Compute      Engine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetIamPolicy(
        GcloudComputeInstancesSetIamPolicyOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// set machine type for Compute      Engine virtual machines
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetMachineType(
        GcloudComputeInstancesSetMachineTypeOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SetMachineType(options, null, cancellationToken);
    }

    /// <summary>
    /// set machine type for Compute      Engine virtual machines
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetMachineType(
        GcloudComputeInstancesSetMachineTypeOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// set the name of a Compute Engine      virtual machine
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetName(
        GcloudComputeInstancesSetNameOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SetName(options, null, cancellationToken);
    }

    /// <summary>
    /// set the name of a Compute Engine      virtual machine
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetName(
        GcloudComputeInstancesSetNameOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// set scheduling options for      Compute Engine virtual machines
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetScheduling(
        GcloudComputeInstancesSetSchedulingOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SetScheduling(options, null, cancellationToken);
    }

    /// <summary>
    /// set scheduling options for      Compute Engine virtual machines
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetScheduling(
        GcloudComputeInstancesSetSchedulingOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// set a service account and      access scopes for a Compute Engine VM instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetServiceAccount(
        GcloudComputeInstancesSetServiceAccountOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SetServiceAccount(options, null, cancellationToken);
    }

    /// <summary>
    /// set a service account and      access scopes for a Compute Engine VM instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetServiceAccount(
        GcloudComputeInstancesSetServiceAccountOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// simulate host      maintenance of VM instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SimulateMaintenanceEvent(
        GcloudComputeInstancesSimulateMaintenanceEventOptions options,
        CancellationToken cancellationToken = default)
    {
        return await SimulateMaintenanceEvent(options, null, cancellationToken);
    }

    /// <summary>
    /// simulate host      maintenance of VM instances
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SimulateMaintenanceEvent(
        GcloudComputeInstancesSimulateMaintenanceEventOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// start a stopped virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Start(
        GcloudComputeInstancesStartOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Start(options, null, cancellationToken);
    }

    /// <summary>
    /// start a stopped virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Start(
        GcloudComputeInstancesStartOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// stop a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Stop(
        GcloudComputeInstancesStopOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Stop(options, null, cancellationToken);
    }

    /// <summary>
    /// stop a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Stop(
        GcloudComputeInstancesStopOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// suspend a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Suspend(
        GcloudComputeInstancesSuspendOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Suspend(options, null, cancellationToken);
    }

    /// <summary>
    /// suspend a virtual machine instance
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Suspend(
        GcloudComputeInstancesSuspendOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// periodically fetch new      output from a virtual machine instance's serial port and display it as      it becomes available
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> TailSerialPortOutput(
        GcloudComputeInstancesTailSerialPortOutputOptions options,
        CancellationToken cancellationToken = default)
    {
        return await TailSerialPortOutput(options, null, cancellationToken);
    }

    /// <summary>
    /// periodically fetch new      output from a virtual machine instance's serial port and display it as      it becomes available
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> TailSerialPortOutput(
        GcloudComputeInstancesTailSerialPortOutputOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// update a Compute Engine      virtual machine access configuration
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateAccessConfig(
        GcloudComputeInstancesUpdateAccessConfigOptions options,
        CancellationToken cancellationToken = default)
    {
        return await UpdateAccessConfig(options, null, cancellationToken);
    }

    /// <summary>
    /// update a Compute Engine      virtual machine access configuration
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateAccessConfig(
        GcloudComputeInstancesUpdateAccessConfigOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// updates Compute Engine virtual      machine instances running container images
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateContainer(
        GcloudComputeInstancesUpdateContainerOptions options,
        CancellationToken cancellationToken = default)
    {
        return await UpdateContainer(options, null, cancellationToken);
    }

    /// <summary>
    /// updates Compute Engine virtual      machine instances running container images
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateContainer(
        GcloudComputeInstancesUpdateContainerOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// update a Compute Engine virtual      machine instance using a configuration file
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateFromFile(
        GcloudComputeInstancesUpdateFromFileOptions options,
        CancellationToken cancellationToken = default)
    {
        return await UpdateFromFile(options, null, cancellationToken);
    }

    /// <summary>
    /// update a Compute Engine virtual      machine instance using a configuration file
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateFromFile(
        GcloudComputeInstancesUpdateFromFileOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    /// <summary>
    /// update a Compute Engine virtual machine
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Update(
        GcloudComputeInstancesUpdateOptions options,
        CancellationToken cancellationToken = default)
    {
        return await Update(options, null, cancellationToken);
    }

    /// <summary>
    /// update a Compute Engine virtual machine
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="loggingOptions">The logging options for this command execution.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Update(
        GcloudComputeInstancesUpdateOptions options,
        CommandLoggingOptions? loggingOptions,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options, loggingOptions, cancellationToken);
    }

    #endregion
}
