// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2026-01-03.
// Do not edit this file manually.
// </auto-generated>

using ModularPipelines.Context;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud services commands.
/// </summary>
public class GcloudEdgecacheServices
{
    private readonly ICommand _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudEdgecacheServices"/> class.
    /// </summary>
    public GcloudEdgecacheServices(ICommand command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// delete an EdgeCacheService resource
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Delete(
        GcloudEdgeCacheServicesDeleteOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudEdgeCacheServicesDeleteOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// show details about an     EdgeCacheService resource
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Describe(
        GcloudEdgeCacheServicesDescribeOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudEdgeCacheServicesDescribeOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// export an EdgeCacheService resource
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Export(
        GcloudEdgeCacheServicesExportOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudEdgeCacheServicesExportOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// import an EdgeCacheService resource
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Import(
        GcloudEdgeCacheServicesImportOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudEdgeCacheServicesImportOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// invalidate the cache for an     EdgeCacheService resource
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> InvalidateCache(
        GcloudEdgeCacheServicesInvalidateCacheOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudEdgeCacheServicesInvalidateCacheOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// list all EdgeCacheService resources in a     project
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> List(
        GcloudEdgeCacheServicesListOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudEdgeCacheServicesListOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// update an EdgeCacheService resource
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> Update(
        GcloudEdgeCacheServicesUpdateOptions? options = default,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineTool(options ?? new GcloudEdgeCacheServicesUpdateOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
