// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Context.Domains.Shell;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud operations commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public class GcloudContainerVmwareOperations
{
    private readonly ICommandContext _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudContainerVmwareOperations"/> class.
    /// </summary>
    public GcloudContainerVmwareOperations(ICommandContext command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// manage Anthos on VMware long running     operations
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ExecuteAsync(
        GcloudContainerVmwareOperationsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudContainerVmwareOperationsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// describe an operation
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DescribeAsync(
        GcloudContainerVmwareOperationsDescribeOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudContainerVmwareOperationsDescribeOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// list operations
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListAsync(
        GcloudContainerVmwareOperationsListOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudContainerVmwareOperationsListOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// poll an operation for completion
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> WaitAsync(
        GcloudContainerVmwareOperationsWaitOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudContainerVmwareOperationsWaitOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
