// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Context.Domains.Shell;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud snapshots commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public class GcloudPreviewComputeSnapshots
{
    private readonly ICommandContext _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudPreviewComputeSnapshots"/> class.
    /// </summary>
    public GcloudPreviewComputeSnapshots(ICommandContext command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// list, describe, and delete Compute     Engine snapshots
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ExecuteAsync(
        GcloudPreviewComputeSnapshotsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudPreviewComputeSnapshotsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// add IAM policy     binding to a Compute Engine snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddIamPolicyBindingAsync(
        GcloudPreviewComputeSnapshotsAddIamPolicyBindingOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudPreviewComputeSnapshotsAddIamPolicyBindingOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// add labels to Google Compute     Engine snapshots
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> AddLabelsAsync(
        GcloudPreviewComputeSnapshotsAddLabelsOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// create Compute Engine snapshots
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> CreateAsync(
        GcloudPreviewComputeSnapshotsCreateOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// delete Compute Engine snapshots
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteAsync(
        GcloudPreviewComputeSnapshotsDeleteOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// describe a Compute Engine     snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DescribeAsync(
        GcloudPreviewComputeSnapshotsDescribeOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// get the IAM policy for a     Compute Engine snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> GetIamPolicyAsync(
        GcloudPreviewComputeSnapshotsGetIamPolicyOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudPreviewComputeSnapshotsGetIamPolicyOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// list Google Compute Engine     snapshots
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListAsync(
        GcloudPreviewComputeSnapshotsListOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudPreviewComputeSnapshotsListOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// remove IAM     policy binding from a Compute Engine snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveIamPolicyBindingAsync(
        GcloudPreviewComputeSnapshotsRemoveIamPolicyBindingOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudPreviewComputeSnapshotsRemoveIamPolicyBindingOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// remove labels from Google     Compute Engine snapshots
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> RemoveLabelsAsync(
        GcloudPreviewComputeSnapshotsRemoveLabelsOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// set the IAM policy for a     Compute Engine snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> SetIamPolicyAsync(
        GcloudPreviewComputeSnapshotsSetIamPolicyOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// test IAM     permissions for a Compute Engine standard or archive snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> TestIamPermissionsAsync(
        GcloudPreviewComputeSnapshotsTestIamPermissionsOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudPreviewComputeSnapshotsTestIamPermissionsOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// update the KMS key of a     Compute Engine standard or archive snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateKmsKeyAsync(
        GcloudPreviewComputeSnapshotsUpdateKmsKeyOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    /// <summary>
    /// update a Compute Engine snapshot
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateAsync(
        GcloudPreviewComputeSnapshotsUpdateOptions options,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options, executionOptions, cancellationToken);
    }

    #endregion
}
