// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Context;
using ModularPipelines.Context.Domains.Shell;
using ModularPipelines.Models;
using ModularPipelines.Options;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Services;

/// <summary>
/// gcloud firewall-policies commands.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public class GcloudRecaptchaFirewallPolicies
{
    private readonly ICommandContext _command;

    /// <summary>
    /// Initializes a new instance of the <see cref="GcloudRecaptchaFirewallPolicies"/> class.
    /// </summary>
    public GcloudRecaptchaFirewallPolicies(ICommandContext command)
    {
        _command = command;
    }

    #region Commands

    /// <summary>
    /// create a Firewall Policy
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> CreateAsync(
        GcloudRecaptchaFirewallPoliciesCreateOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudRecaptchaFirewallPoliciesCreateOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// delete one or more reCAPTCHA     Firewall Policies
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DeleteAsync(
        GcloudRecaptchaFirewallPoliciesDeleteOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudRecaptchaFirewallPoliciesDeleteOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// describe reCAPTCHA Firewall     Policy
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> DescribeAsync(
        GcloudRecaptchaFirewallPoliciesDescribeOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudRecaptchaFirewallPoliciesDescribeOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// list reCAPTCHA Firewall Policies
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ListAsync(
        GcloudRecaptchaFirewallPoliciesListOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudRecaptchaFirewallPoliciesListOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// reorder all Firewall Policies
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> ReorderAsync(
        GcloudRecaptchaFirewallPoliciesReorderOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudRecaptchaFirewallPoliciesReorderOptions(), executionOptions, cancellationToken);
    }

    /// <summary>
    /// update a Firewall Policy
    /// </summary>
    /// <param name="options">The command options.</param>
    /// <param name="executionOptions">The execution configuration options.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The command result.</returns>
    public virtual async Task<CommandResult> UpdateAsync(
        GcloudRecaptchaFirewallPoliciesUpdateOptions? options = null,
        CommandExecutionOptions? executionOptions = null,
        CancellationToken cancellationToken = default)
    {
        return await _command.ExecuteCommandLineToolAsync(options ?? new GcloudRecaptchaFirewallPoliciesUpdateOptions(), executionOptions, cancellationToken);
    }

    #endregion
}
