// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://cloud.google.com/sdk/gcloud/reference/ai/hp-tuning-jobs/stream-logs
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// stream logs from a running Vertex AI     hyperparameter tuning job
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "1.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("ai", "hp-tuning-jobs", "stream-logs")]
public record GcloudAiHpTuningJobsStreamLogsOptions : GcloudOptions
{
    /// <summary>
    /// Output multiline log messages as single records.
    /// </summary>
    [CliFlag("--allow-multiline-logs")]
    public bool? AllowMultilineLogs { get; set; }

    [CliOption("--polling-interval", Format = OptionFormat.EqualsSeparated)]
    public string? PollingInterval { get; set; }

    /// <summary>
    /// If set, display only the logs for this particular task.
    /// </summary>
    [CliOption("--task-name", Format = OptionFormat.EqualsSeparated)]
    public string? TaskName { get; set; }

}
