// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://cloud.google.com/sdk/gcloud/reference/compute/reservations/blocks/perform-maintenance
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// perform     maintenance on a reservation block within a reservation
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("compute", "reservations", "blocks", "perform-maintenance")]
public record GcloudComputeReservationsBlocksPerformMaintenanceOptions : GcloudOptions
{
    /// <summary>
    /// perform     maintenance on a reservation block within a reservation
    /// </summary>
    /// <param name="BlockName">The name of the reservation block.</param>
    /// <param name="Reservation">Name of the reservation to perform-maintenance.</param>
    public GcloudComputeReservationsBlocksPerformMaintenanceOptions(
        string BlockName,
        string Reservation
    )
    {
        global::System.ArgumentNullException.ThrowIfNull(BlockName);
        this.BlockName = BlockName;
        global::System.ArgumentNullException.ThrowIfNull(Reservation);
        this.Reservation = Reservation;
    }

    public void Deconstruct(out string BlockName, out string Reservation)
    {
        BlockName = this.BlockName;
        Reservation = this.Reservation;
    }

    /// <summary>
    /// The name of the reservation block.
    /// </summary>
    [CliOption("--block-name", Format = OptionFormat.EqualsSeparated)]
    public string BlockName { get; private init; }

    /// <summary>
    /// The maintenance scope to set for the reservation block. SCOPE must be one of: all Perform maintenance on all hosts in the reservation block. running Perform maintenance only on the hosts in the reservation block that have running VMs. unused Perform maintenance only on the hosts in the reservation block that don't have running VMs.
    /// </summary>
    [CliOption("--scope", Format = OptionFormat.EqualsSeparated)]
    public string? Scope { get; set; }

    /// <summary>
    /// Zone of the reservation to perform-maintenance. If not specified and the compute/zone property isn't set, you might be prompted to select a zone (interactive mode only). To avoid prompting when this flag is omitted, you can set the compute/zone property: $ gcloud config set compute/zone ZONE A list of zones can be fetched by running: $ gcloud compute zones list To unset the property, run: $ gcloud config unset compute/zone Alternatively, the zone can be stored in the environment variable CLOUDSDK_COMPUTE_ZONE.
    /// </summary>
    [CliOption("--zone", Format = OptionFormat.EqualsSeparated)]
    public string? Zone { get; set; }

    /// <summary>
    /// Name of the reservation to perform-maintenance.
    /// </summary>
    [CliArgument(0, Phase = CommandLinePhase.EarlyOperand, Required = true)]
    public string Reservation { get; private init; }

}
