// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://cloud.google.com/sdk/gcloud/reference/compute/interconnects/application-awareness/delete
// Do not edit this file manually.
// </auto-generated>

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// delete     application awareness configuration of a Compute Engine interconnect
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "")]
[ExcludeFromCodeCoverage]
[CliSubCommand("compute", "interconnects", "application-awareness", "delete")]
public record GcloudComputeInterconnectsApplicationAwarenessDeleteOptions(
    [property: CliArgument(0, Placement = ArgumentPlacement.BeforeOptions)] string Name
) : GcloudOptions
{
}
