// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Source: https://cloud.google.com/sdk/gcloud/reference/app/logs/tail
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// streams logs for App Engine apps
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("app", "logs", "tail")]
public record GcloudAppLogsTailOptions : GcloudOptions
{
    [CliOption("--level", Format = OptionFormat.EqualsSeparated)]
    public string? Level { get; set; }

    [CliOption("--logs", Format = OptionFormat.EqualsSeparated, AllowMultiple = true)]
    public IEnumerable<string>? Logs { get; set; }

    [CliOption("--service", Format = OptionFormat.EqualsSeparated)]
    public string? Service { get; set; }

    [CliOption("--version", Format = OptionFormat.EqualsSeparated)]
    public string? Version { get; set; }

}
