// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Source: https://cloud.google.com/sdk/gcloud/reference/compute/storage-pools
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// read and manipulate storage pools
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("compute", "storage-pools")]
public record GcloudComputeStoragePoolsOptions : GcloudOptions
{
}
