// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://cloud.google.com/sdk/gcloud/reference/iap/web
// Do not edit this file manually.
// </auto-generated>

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// manage IAP web policies
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "")]
[ExcludeFromCodeCoverage]
[CliSubCommand("iap", "web")]
public record GcloudIapWebOptions : GcloudOptions
{
}
