// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-08.
// Source: https://cloud.google.com/sdk/gcloud/reference/iam/service-accounts/keys
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// manage service account keys
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("iam", "service-accounts", "keys")]
public record GcloudIamServiceAccountsKeysOptions : GcloudOptions
{
}
