// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://cloud.google.com/sdk/gcloud/reference/artifacts/locations
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// manage Artifact Registry resource locations
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "1.0.0")]
[ExcludeFromCodeCoverage]
[CliSubCommand("artifacts", "locations")]
public record GcloudArtifactsLocationsOptions : GcloudOptions
{
}
