// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Source: https://cloud.google.com/sdk/gcloud/reference/redis/clusters/get-cluster-certificate-authority
// Do not edit this file manually.
// </auto-generated>

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// get the     certificate authority information for a Memorystore for Redis Cluster     instance
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "")]
[ExcludeFromCodeCoverage]
[CliSubCommand("redis", "clusters", "get-cluster-certificate-authority")]
public record GcloudRedisClustersGetClusterCertificateAuthorityOptions : GcloudOptions
{
}
