// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-08.
// Source: https://cloud.google.com/sdk/gcloud/reference/compute/backend-services/import
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Google.Options;

namespace ModularPipelines.Google.Options;

/// <summary>
/// import a backend service
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("compute", "backend-services", "import")]
public record GcloudComputeBackendServicesImportOptions(
    [property: CliArgument(0, Name = "BACKEND_SERVICE_NAME")] string BackendServiceName
) : GcloudOptions
{
    /// <summary>
    /// Path to a YAML file containing configuration export data.      Alternatively, you may omit this flag to read from standard input.For a      schema describing the export/import format, see:      $CLOUDSDKROOT\lib\googlecloudsdk\schemas\compute\v1\BackendService.yaml.          Note: $CLOUDSDKROOT represents the Google Cloud CLI's installation directory.      At most one of these can be specified:       --global       If set, the backend service is global.       --region=REGION       Region of the backend service to import. Overrides the default       compute/region property value for this command invocation.
    /// </summary>
    [CliOption("--source", Format = OptionFormat.EqualsSeparated)]
    public string? Source { get; set; }

}
