<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GeneratedOptionsAssembly>ModularPipelines.Git</GeneratedOptionsAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ModularPipelines.Git\ModularPipelines.Git.csproj" />
    <PackageReference Include="Moq" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>
  <Import Project="..\GeneratedOptionsSmokeTests\GeneratedOptionsSmokeTests.props" />
</Project>
