// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Docker.Options;

namespace ModularPipelines.Docker.Options;

/// <summary>
/// Create a new image based on source images
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("builder", "imagetools", "create")]
public record DockerBuilderImagetoolsCreateOptions : DockerOptions
{
    /// <summary>
    /// Add annotation to the image
    /// </summary>
    [CliOption("--annotation", Format = OptionFormat.EqualsSeparated, AllowMultiple = true)]
    public IEnumerable<string>? Annotation { get; set; }

    /// <summary>
    /// Append to existing manifest
    /// </summary>
    [CliFlag("--append")]
    public bool? Append { get; set; }

    /// <summary>
    /// Override the configured builder instance (default "default")
    /// </summary>
    [CliOption("--builder", Format = OptionFormat.EqualsSeparated)]
    public string? Builder { get; set; }

    /// <summary>
    /// Enable debug logging
    /// </summary>
    [CliFlag("--debug", ShortForm = "-D")]
    public bool? Debug { get; set; }

    /// <summary>
    /// Show final image instead of pushing
    /// </summary>
    [CliFlag("--dry-run")]
    public bool? DryRun { get; set; }

    /// <summary>
    /// Read source descriptor from file
    /// </summary>
    [CliOption("--file", ShortForm = "-f", Format = OptionFormat.EqualsSeparated, AllowMultiple = true)]
    public IEnumerable<string>? File { get; set; }

    /// <summary>
    /// Filter specified platforms of target image
    /// </summary>
    [CliOption("--platform", ShortForm = "-p", Format = OptionFormat.EqualsSeparated, AllowMultiple = true)]
    public IEnumerable<string>? Platform { get; set; }

    /// <summary>
    /// When only a single source is specified, prefer outputting an image index or manifest list instead of performing a carbon copy (default true)
    /// </summary>
    [CliFlag("--prefer-index")]
    public bool? PreferIndex { get; set; }

    /// <summary>
    /// Set type of progress output ("auto", "none", "plain", "rawjson", "tty"). Use plain to show container output (default "auto")
    /// </summary>
    [CliOption("--progress", Format = OptionFormat.EqualsSeparated)]
    public string? Progress { get; set; }

    /// <summary>
    /// Set reference for new image
    /// </summary>
    [CliOption("--tag", ShortForm = "-t", Format = OptionFormat.EqualsSeparated, AllowMultiple = true)]
    public IEnumerable<string>? Tag { get; set; }

    [CliArgument(0, Name = "OPTIONS")]
    public string? Options { get; set; }

    [CliArgument(1, Name = "SOURCE")]
    public string? Source { get; set; }

}
