// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator on 2025-12-28.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.Diagnostics.CodeAnalysis;
using ModularPipelines.Attributes;
using ModularPipelines.Docker.Options;

namespace ModularPipelines.Docker.Options;

/// <summary>
/// Remove one or more containers
/// </summary>
[ExcludeFromCodeCoverage]
[CliSubCommand("rm")]
public record DockerRmOptions : DockerOptions
{
    /// <summary>
    /// Force the removal of a running container (uses SIGKILL)
    /// </summary>
    [CliFlag("--force", ShortForm = "-f")]
    public bool? Force { get; set; }

    /// <summary>
    /// Remove the specified link
    /// </summary>
    [CliFlag("--link", ShortForm = "-l")]
    public bool? Link { get; set; }

    /// <summary>
    /// Remove anonymous volumes associated with the container
    /// </summary>
    [CliFlag("--volumes", ShortForm = "-v")]
    public bool? Volumes { get; set; }

    [CliArgument(0, Name = "OPTIONS")]
    public string? Options { get; set; }

    [CliArgument(1, Name = "CONTAINER")]
    public string? Container { get; set; }

}
