// <auto-generated>
// This file was generated by ModularPipelines.OptionsGenerator.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using System.CodeDom.Compiler;
using ModularPipelines.Attributes;

namespace ModularPipelines.AmazonWebServices.Enums;

/// <summary>
/// Allowed values for --targettaskrunstatus.
/// </summary>
[GeneratedCode("ModularPipelines.OptionsGenerator", "2.0.0")]
public enum AwsDeadlineCreateJobTargetTaskRunStatus
{
    [EnumValue("READY")]
    Ready = 1,

    [EnumValue("SUSPENDED")]
    Suspended = 2
}
